import React, { useState } from 'react';
import { NavLink, Link, useLocation } from 'react-router-dom';
import { Layers3, Activity, ChartNoAxesCombined, ClipboardCheck, UsersRound, FileChartColumn, Settings2, LogOut, Monitor, ChevronDown, Menu, X, ArrowUpRight, ShieldCheck, Bell, CircleHelp } from 'lucide-react';
import { useApp } from '../App';
import { initials } from '../lib/api';
import { Badge, Button, Modal } from './Common';
import { Brand } from './Brand';
import { CreatorSidebar } from './CreatorSidebar';
const nav = [['/', 'Criadoras', Layers3], ['/operacao', 'Operação', Activity], ['/vendas', 'Vendas', ChartNoAxesCombined], ['/qualidade', 'Qualidade', ClipboardCheck], ['/equipe', 'Equipe e turnos', UsersRound], ['/relatorios', 'Relatórios', FileChartColumn]];
export const Shell = ({ children }) => {
  const { user, config, creators, station, logout, isDesktop, desktopDevice } = useApp(); const [mobile, setMobile] = useState(false), [help, setHelp] = useState(false), [alerts, setAlerts] = useState(false);
  const route = useLocation().pathname; const active = nav.find(n => n[0] === route)?.[1] || (route.startsWith('/navegador/') ? 'Navegador' : route === '/computadores' ? 'Computadores' : 'Configurações');
  return <div className="app-shell"><aside className={`sidebar ${mobile ? 'open' : ''}`}><div className="brand-row"><Link data-testid="brand-home" to="/" aria-label="Alta Core — início" onClick={() => setMobile(false)}><Brand variant="white"/></Link><button className="mobile-close icon-btn" aria-label="Fechar menu" data-testid="close-menu" onClick={() => setMobile(false)}><X size={20}/></button></div>
    <div className="workspace"><div className="workspace-icon">{initials(config?.agency_name)}</div><div><strong data-testid="workspace-name">{config?.agency_name}</strong><small data-testid="workspace-caption">Workspace da agência</small></div><ChevronDown size={14}/></div>
    <span className="nav-caption" data-testid="nav-caption">WORKSPACE</span><nav>{nav.filter(n => user.role === 'manager' || ['/', '/equipe'].includes(n[0])).map(([path, label, Icon]) => <NavLink data-testid={`nav-${path === '/' ? 'creators' : path.slice(1)}`} key={path} end to={path} onClick={() => setMobile(false)} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Icon size={19}/><span>{label}</span>{path === '/' && <span className="nav-count" data-testid="nav-creator-count">{creators.length}</span>}</NavLink>)}</nav>
    <CreatorSidebar creators={creators} onNavigate={() => setMobile(false)}/>
    <div className="sidebar-bottom"><div className="station-mini"><div><Monitor size={17}/><strong data-testid="station-mini-title">{isDesktop ? 'Este computador' : 'Alta Core Desktop'}</strong><i className={isDesktop && desktopDevice?.status === 'approved' ? 'online-dot' : 'offline-dot'}/></div><p data-testid="station-mini-status">{isDesktop ? desktopDevice?.status === 'approved' ? 'Aplicativo autorizado' : 'Aguardando autorização' : 'Atenda pelo aplicativo Windows'}</p><Link to={isDesktop ? '/computadores' : '/baixar'} data-testid="connect-station-link" onClick={() => setMobile(false)}>{isDesktop ? 'Gerenciar computador' : 'Instalar aplicativo'} <ArrowUpRight size={14}/></Link></div>
    {user.role === 'manager' && <NavLink to="/configuracoes" data-testid="nav-configuracoes" className="nav-item" onClick={() => setMobile(false)}><Settings2 size={18}/>Configurações</NavLink>}
    <NavLink to="/computadores" data-testid="nav-computadores" className="nav-item" onClick={() => setMobile(false)}><Monitor size={18}/>Computadores</NavLink>
    <Link to="/baixar" data-testid="nav-download-desktop" className="sidebar-install-link" onClick={() => setMobile(false)}><Monitor size={16}/>{isDesktop ? 'Aplicativo e instalação' : 'Instalar Alta Core'}<ArrowUpRight size={14}/></Link>
    <div className="user-block"><div className="avatar user-avatar">{initials(user.name)}</div><div><strong data-testid="signed-in-name">{user.name}</strong><small data-testid="signed-in-role">{user.role === 'manager' ? 'Gestor da agência' : 'Chatter'}</small></div><button title="Sair da conta" aria-label="Sair da conta" data-testid="logout-button" className="icon-btn" onClick={logout}><LogOut size={17}/></button></div></div></aside>
    {mobile && <button aria-label="Fechar navegação" data-testid="menu-backdrop" className="menu-backdrop" onClick={() => setMobile(false)}/>}
    <div className="main-layout"><header className="topbar"><div className="breadcrumb"><button data-testid="open-menu" aria-label="Abrir menu" className="mobile-toggle icon-btn" onClick={() => setMobile(true)}><Menu size={21}/></button><span>Workspace</span><span className="slash">/</span><strong data-testid="breadcrumb-current">{active}</strong></div><div className="topbar-right"><span className="timezone" data-testid="timezone">Horário de Brasília <span>UTC−3</span></span><span className="topbar-divider"/><button data-testid="help-button" title="Privacidade e limites" className="icon-btn" onClick={() => setHelp(true)}><CircleHelp size={19}/></button><button data-testid="alerts-button" title="Avisos da operação" className="icon-btn" onClick={() => setAlerts(true)}><Bell size={19}/><i className="notification-dot"/></button><div className="avatar small-avatar">{initials(user.name)}</div></div></header>
    <main>{children}</main><footer className="page-footer"><span data-testid="footer-brand">Alta Core · Um produto Alta Agency.</span><span data-testid="footer-privacy"><ShieldCheck size={13}/>Dados mínimos. Sessões locais.</span></footer></div>
    <Modal title="Privacidade por princípio" open={help} onClose={() => setHelp(false)} id="help-modal"><p data-testid="privacy-summary" className="body-muted">Somente métricas e avaliações estruturadas. Senhas, cookies e conteúdo das conversas permanecem no computador da agência. Não há integração com a API da Privacy.</p><p data-testid="coverage-summary" className="body-muted">A amostra é parcial. A compatibilidade das telas depende de validação na conta autorizada; a atribuição por turno não comprova autoria ou causalidade de uma venda.</p></Modal>
    <Modal title="Avisos da operação" open={alerts} onClose={() => setAlerts(false)} id="alerts-modal"><Badge testId="alert-station-state" tone={station?.online ? 'green' : 'amber'}>{station?.online ? 'Estação conectada' : 'Estação desconectada'}</Badge><p data-testid="alert-detail" className="body-muted">{station?.online ? 'Confira o estado de leitura de cada criadora. Conexão não significa cobertura integral.' : 'Não há coleta local em andamento. Indicadores sem observação permanecem indisponíveis.'}</p>{!config?.storage_allowed && <p data-testid="alert-retention" className="body-muted">O armazenamento de métricas aguarda confirmação do gestor.</p>}</Modal>
  </div>;
};