import React, { useState, useEffect } from 'react';
import { nextPhrase, greeting, SIGNATURE } from '../lib/motivation';
import { NavLink, Link, useLocation } from 'react-router-dom';
import { Sparkles, Megaphone, Layers3, MoonStar, Activity, ChartNoAxesCombined, TrendingUp, ClipboardCheck, UsersRound, FileChartColumn, Settings2, LogOut, ChevronDown, Menu, X, ArrowUpRight, ShieldCheck, Bell, CircleHelp, Puzzle, Camera } from 'lucide-react';
import { useApp } from '../App';
import { initials } from '../lib/api';
import { Badge, Modal, Avatar } from './Common';
import { Brand } from './Brand';
import { CreatorSidebar } from './CreatorSidebar';
import { canContent } from '../pages/Content';
const nav = [['/', 'Criadoras', Layers3], ['/operacao', 'Operação', Activity], ['/vendas', 'Vendas', ChartNoAxesCombined], ['/desempenho', 'Desempenho', TrendingUp], ['/assinantes', 'Assinantes', UsersRound], ['/qualidade', 'Qualidade', ClipboardCheck], ['/equipe', 'Equipe e turnos', UsersRound], ['/relatorios', 'Relatórios', FileChartColumn]];
export const Shell = ({ children }) => {
  const { user, config, creators, logout } = useApp(); const [mobile, setMobile] = useState(false), [help, setHelp] = useState(false), [alerts, setAlerts] = useState(false);
  // boas-vindas logo depois do login: primeiro nome + frase motivacional (some em 9 s ou no "Bora!")
  const [welcome, setWelcome] = useState(null);
  useEffect(() => { let flag = null; try { flag = sessionStorage.getItem('alta-welcome'); sessionStorage.removeItem('alta-welcome'); } catch {} if (flag && user) { setWelcome(nextPhrase(user.id)); const t = setTimeout(() => setWelcome(null), 9000); return () => clearTimeout(t); } }, [user?.id]);
  const route = useLocation().pathname; const active = nav.find(n => n[0] === route)?.[1] || (route === '/minha-conta' ? 'Minha conta' : route === '/plantao' ? 'Plantão noturno' : route === '/consumo-ia' ? 'Consumo da IA' : route === '/conteudo' ? 'Conteúdo e disparos' : 'Configurações');
  return <div className="app-shell">{welcome && <div className="welcome-overlay" data-testid="welcome" onClick={() => setWelcome(null)}><div className="welcome-card" onClick={e => e.stopPropagation()}><Avatar user={user} className="welcome-photo"/><div className="welcome-hi">{greeting(user.name)}</div><p>{welcome}</p><div className="welcome-sign">{SIGNATURE}</div><button onClick={() => setWelcome(null)}>Bora!</button></div></div>}<aside className={`sidebar ${mobile ? 'open' : ''}`}><div className="brand-row"><Link data-testid="brand-home" to="/" aria-label="Alta Pulse — início" onClick={() => setMobile(false)}><Brand variant="white"/></Link><button className="mobile-close icon-btn" aria-label="Fechar menu" data-testid="close-menu" onClick={() => setMobile(false)}><X size={20}/></button></div>
    <div className="workspace"><div className="workspace-icon">{initials(config?.agency_name)}</div><div><strong data-testid="workspace-name">{config?.agency_name}</strong><small data-testid="workspace-caption">Workspace da agência</small></div><ChevronDown size={14}/></div>
    <span className="nav-caption" data-testid="nav-caption">WORKSPACE</span><nav>{nav.filter(n => user.role === 'manager' || user.role === 'supervisor' || ['/', '/equipe'].includes(n[0])).map(([path, label, Icon]) => <NavLink data-testid={`nav-${path === '/' ? 'creators' : path.slice(1)}`} key={path} end to={path} onClick={() => setMobile(false)} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><Icon size={19}/><span>{label}</span>{path === '/' && <span className="nav-count" data-testid="nav-creator-count">{creators.length}</span>}</NavLink>)}</nav>
    <CreatorSidebar creators={creators} onNavigate={() => setMobile(false)}/>
    <div className="sidebar-bottom"><div className="station-mini"><div><Puzzle size={17}/><strong data-testid="station-mini-title">Alta Pulse desktop</strong></div><p data-testid="station-mini-status">Os chatters atendem pelo app, com um perfil isolado por criadora.</p><Link to="/instalar" data-testid="connect-station-link" onClick={() => setMobile(false)}>Instalar o app <ArrowUpRight size={14}/></Link></div>
    {(user.owner || (user.perms || []).includes('plantao')) && <NavLink to="/plantao" data-testid="nav-plantao" className="nav-item" onClick={() => setMobile(false)}><MoonStar size={18}/>Plantão noturno</NavLink>}
    {user.owner && <NavLink to="/consumo-ia" data-testid="nav-consumo-ia" className="nav-item" onClick={() => setMobile(false)}><Sparkles size={18}/>Consumo da IA</NavLink>}
    {canContent(user) && <NavLink to="/conteudo" data-testid="nav-conteudo" className="nav-item" onClick={() => setMobile(false)}><Megaphone size={18}/>Conteúdo e disparos</NavLink>}
    {user.role === 'manager' && <NavLink to="/configuracoes" data-testid="nav-configuracoes" className="nav-item" onClick={() => setMobile(false)}><Settings2 size={18}/>Configurações</NavLink>}
    <Link to="/instalar" data-testid="nav-install-extension" className="sidebar-install-link" onClick={() => setMobile(false)}><Puzzle size={16}/>Extensão para Chrome<ArrowUpRight size={14}/></Link>
    <div className="user-block"><Avatar user={user} className="user-avatar"/><Link to="/minha-conta" data-testid="my-account-link" className="account-user-link" onClick={() => setMobile(false)}><strong data-testid="signed-in-name">{user.name}</strong><small data-testid="signed-in-role">Minha conta · Alterar senha</small></Link><button title="Sair da conta" aria-label="Sair da conta" data-testid="logout-button" className="icon-btn" onClick={logout}><LogOut size={17}/></button></div></div></aside>
    {mobile && <button aria-label="Fechar navegação" data-testid="menu-backdrop" className="menu-backdrop" onClick={() => setMobile(false)}/>}
    <div className="main-layout"><header className="topbar"><div className="breadcrumb"><button data-testid="open-menu" aria-label="Abrir menu" className="mobile-toggle icon-btn" onClick={() => setMobile(true)}><Menu size={21}/></button><span>Workspace</span><span className="slash">/</span><strong data-testid="breadcrumb-current">{active}</strong></div><div className="topbar-right"><span className="timezone" data-testid="timezone">Horário de Brasília <span>UTC−3</span></span><span className="topbar-divider"/><button data-testid="help-button" title="Privacidade e limites" className="icon-btn" onClick={() => setHelp(true)}><CircleHelp size={19}/></button><button data-testid="alerts-button" title="Avisos da operação" className="icon-btn" onClick={() => setAlerts(true)}><Bell size={19}/><i className="notification-dot"/></button>{!user.avatar && <Link to="/minha-conta" className="photo-nudge" data-testid="photo-nudge"><Camera size={14}/>Colocar sua foto</Link>}<Link to="/minha-conta" title="Minha conta · foto de perfil" data-testid="topbar-avatar"><Avatar user={user} className="small-avatar"/></Link></div></header>
    <main>{children}</main><footer className="page-footer"><span data-testid="footer-brand">Alta Pulse · Um produto Alta Agency.</span><span data-testid="footer-privacy"><ShieldCheck size={13}/>Dados mínimos. Sem API da Privacy.</span></footer></div>
    <Modal title="Privacidade por princípio" open={help} onClose={() => setHelp(false)} id="help-modal"><p data-testid="privacy-summary" className="body-muted">Somente métricas e avaliações estruturadas. Cookies e conteúdo das conversas permanecem no computador do chatter; senhas só existem no cofre criptografado, sob controle do gestor. Não há integração com a API da Privacy.</p><p data-testid="coverage-summary" className="body-muted">A amostra é parcial. A leitura de tempo de resposta e vendas depende de validação das telas; presença e turnos já são registrados pela extensão.</p></Modal>
    <Modal title="Avisos da operação" open={alerts} onClose={() => setAlerts(false)} id="alerts-modal"><Badge testId="alert-station-state" tone="neutral">Monitoramento pela extensão Chrome</Badge><p data-testid="alert-detail" className="body-muted">Cada chatter instala a extensão no próprio Chrome e escolhe a criadora atendida. A presença aparece quando a Privacy está aberta.</p>{!config?.storage_allowed && <p data-testid="alert-retention" className="body-muted">O armazenamento de métricas aguarda confirmação do gestor.</p>}</Modal>
  </div>;
};
