import React, { useEffect, useState } from 'react';
import { Download, FlaskConical, ShieldCheck, Monitor, MousePointer2, ArrowRight, RefreshCw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useApp } from '../App';
import { api, errorText } from '../lib/api';
import { PageHeading, Button, Notice, Badge } from '../components/Common';
import './ChromePilot.css';

export default function ChromePilot() {
  const { isDesktop } = useApp(); const isPilot = window.altaDesktop?.engine === 'chrome-pilot';
  const [release, setRelease] = useState(null), [error, setError] = useState('');
  const load = async () => { setError(''); try { setRelease((await api.get('/desktop/pilot/release')).data); } catch (e) { setError(errorText(e)); } };
  useEffect(() => { load(); }, []);
  return <><PageHeading eyebrow="PILOTO EXPERIMENTAL · WINDOWS" title="Chrome real. Um novo caminho." description="Uma prova de conceito separada, sem substituir seu Alta Pulse atual."><Badge testId="chrome-pilot-status" tone="amber">Experimental</Badge></PageHeading>
    <div className="chrome-pilot-intro"><div className="pilot-emblem"><FlaskConical size={36}/></div><div><h2 data-testid="pilot-product-title">Alta Pulse — Piloto Chrome</h2><p data-testid="pilot-product-description">Usa o Google Chrome instalado no seu computador e tenta encaixar a janela na área de atendimento. Não simula a identidade do Chrome.</p>{release?.available ? <a className="desktop-download-button" data-testid="download-chrome-pilot" href={`${process.env.REACT_APP_BACKEND_URL}/api/desktop/pilot/download/windows`} download><Download size={16}/>Baixar piloto para Windows</a> : <Button variant="outline" data-testid="pilot-download-unavailable" disabled>Preparando piloto</Button>}<small data-testid="pilot-release-details">{release?.available ? `v${release.version} · Windows 11 x64 · ${(release.size_bytes / 1048576).toFixed(0)} MB · Requer Google Chrome instalado` : 'Distribuição de teste disponível para gestores.'}</small></div></div>
    {error && <Notice id="pilot-load-error" tone="danger">{error}<Button variant="ghost" data-testid="retry-pilot-release" onClick={load}><RefreshCw size={14}/>Tentar novamente</Button></Notice>}
    {isDesktop && <Notice id="pilot-current-app">{isPilot ? 'Você está no aplicativo piloto. Selecione uma criadora autorizada na lateral.' : 'Você está no aplicativo regular. O piloto será instalado com outro atalho e outro perfil local.'}</Notice>}
    <div className="pilot-features"><section><Monitor size={21}/><h2>Chrome instalado</h2><p>O piloto inicia uma instância própria do navegador. Só mostra “encaixado” quando a janela é confirmada dentro do aplicativo.</p></section><section><ShieldCheck size={21}/><h2>Perfis separados</h2><p>Perfis novos para cada criadora, sem copiar sessões do Chrome pessoal nem da versão atual. O primeiro login continua manual.</p></section><section><MousePointer2 size={21}/><h2>Operação manual</h2><p>Mouse e teclado atuam diretamente no Chrome. Sem API Privacy, leitura de conversas, troca de identidade ou envio de relatórios.</p></section></div>
    <Notice id="pilot-unsupported-warning" tone="amber">O encaixe não é uma integração oficial do Chrome. Pode haver incompatibilidades de janela, foco, escala de tela e pop-ups. O novo perfil pode continuar recebendo bloqueio da Privacy. Este piloto ainda não foi validado em Windows real.</Notice>
    <Notice id="pilot-signature-warning" tone="amber">O instalador e o componente local ainda não têm assinatura digital. Se o Windows bloquear, não desative proteções para executar. A versão regular e seus dados não são substituídos.</Notice>
    <section className="pilot-first-use"><h2 data-testid="pilot-first-use-title">Primeiro uso</h2><ol data-testid="pilot-first-use-steps"><li>Instale o arquivo e abra o atalho <strong>Alta Pulse - Piloto Chrome</strong>.</li><li>Entre com seu acesso pessoal. O piloto terá uma autorização de computador própria.</li><li>Feche o perfil dessa criadora na versão regular antes de abri-lo no piloto. Não precisa desinstalar a versão anterior.</li><li>Selecione a criadora na lateral e abra o perfil; o Chrome pessoal não será reutilizado.</li><li>Se o encaixe funcionar, use o site manualmente. O estado da conta e a aceitação da Privacy não são verificados pelo piloto.</li></ol><Link data-testid="pilot-go-devices" className="text-link" to="/computadores">Ver computadores autorizados<ArrowRight size={14}/></Link></section>
    {release?.available && <details className="pilot-checksum"><summary data-testid="pilot-checksum-toggle">Integridade do arquivo</summary><code data-testid="pilot-checksum">SHA-256: {release.sha256}</code></details>}
  </>;
}