import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Search, LayoutGrid, List, UsersRound, Monitor, Timer, ArrowUpRight, Ellipsis, Play, Pause, Square, Settings2, Layers3, ShieldCheck, Activity, ArrowRight, Pencil, Trash2 } from 'lucide-react';
import { toast } from 'sonner';
import { useApp } from '../App';
import { api, initials, errorText, dateTime } from '../lib/api';
import { PageHeading, Badge, Button, Field, Select, Modal, Submit, FormError, Stat, Notice, Empty } from '../components/Common';

export default function Creators() {
  const { user, creators, station, refresh } = useApp(); const [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [view, setView] = useState('grid');
  const [form, setForm] = useState(null), [color, setColor] = useState('green'), [busy, setBusy] = useState(false), [error, setError] = useState(''), [details, setDetails] = useState(null), [deleteReason, setDeleteReason] = useState('');
  const isManager = user.role === 'manager', active = creators.filter(c => c.shift && !c.shift.paused).length;
  const filtered = creators.filter(c => `${c.name} ${c.handle}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || filter === 'active' && c.shift && !c.shift.paused || filter === 'paused' && c.shift?.paused || filter === 'idle' && !c.shift));
  const openForm = (c = {}) => { setForm(c); setColor(c.color || 'green'); setError(''); setDetails(null); };
  async function save(e) { e.preventDefault(); setBusy(true); setError(''); const body = { ...Object.fromEntries(new FormData(e.currentTarget)), color };
    try { await (form.id ? api.patch(`/creators/${form.id}`, body) : api.post('/creators', body)); await refresh(); setForm(null); toast.success(form.id ? 'Cadastro atualizado.' : 'Criadora cadastrada.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  async function action(c, type) { setBusy(true); try {
    if (type === 'browser') { const r = await api.post(`/creators/${c.id}/browser`); toast.success(r.data.message); }
    else if (type === 'start') { await api.post('/shifts', { creator_id: c.id }); toast.success('Seu turno começou.'); }
    else { await api.post(`/shifts/${c.shift.id}/action`, { action: type }); toast.success(type === 'end' ? 'Turno encerrado.' : type === 'pause' ? 'Atendimento pausado.' : 'Atendimento retomado.'); }
    await refresh();
  } catch (e) { toast.error(errorText(e)); } finally { setBusy(false); } }
  const state = c => c.review ? ['Em revisão', 'amber'] : c.shift?.paused ? ['Pausado', 'amber'] : c.shift ? ['Em atendimento', 'green'] : ['Sem turno ativo', 'neutral'];
  const observation = c => !station?.online ? (station?.id ? 'Conexão interrompida' : 'Sem conexão local') : c.browser?.state === 'interrupted' ? 'Acompanhamento interrompido' : c.browser?.state !== 'open' ? 'Navegador fechado' : ({ partial: 'Amostra parcial', paused: 'Leitura pausada', no_data: 'Sem dados suficientes', interrupted: 'Leitura interrompida', validation_required: 'Leitura não validada' }[c.browser?.observation_state] || 'Sem dados observados');
  return <><PageHeading title="Criadoras" description="Cada perfil no seu espaço. Toda a operação à vista."><span className="heading-date" data-testid="today-date">{new Intl.DateTimeFormat('pt-BR', { day: 'numeric', month: 'long', timeZone: 'America/Sao_Paulo' }).format(new Date())}</span>{isManager && <Button data-testid="add-creator-button" onClick={() => openForm()}><Plus size={17}/>Nova criadora</Button>}</PageHeading>
    <div className="stats-grid"><Stat id="creators-total" label="Criadoras cadastradas" value={creators.length.toString().padStart(2, '0')} caption="Perfis independentes" icon={UsersRound}/><Stat id="creators-active" label="Em atendimento" value={active.toString().padStart(2, '0')} caption="Com turno ativo agora" icon={Activity} tone="green"/><Stat id="creators-browsers" label="Navegadores abertos" value={station?.online ? creators.filter(c => c.browser?.state === 'open').length.toString().padStart(2, '0') : '—'} caption={station?.online ? 'Na estação conectada' : 'Estação não conectada'} icon={Monitor}/><Stat id="creators-waiting" label="Aguardando turno" value={creators.filter(c => !c.shift).length.toString().padStart(2, '0')} caption="Sem operador responsável" icon={Timer}/></div>
    {!station?.online && <div className="connection-banner" data-testid="station-connection-banner"><div className="connection-icon"><Monitor size={22}/></div><div><strong data-testid="connection-banner-title">Seu workspace está pronto. Conecte sua estação.</strong><p data-testid="connection-banner-description">Os perfis e as sessões ficam no computador Windows da sua agência.</p></div>{isManager && <Link to="/configuracoes" data-testid="setup-station-link">Configurar estação<ArrowUpRight size={16}/></Link>}</div>}
    <section className="creator-section"><div className="section-heading"><div className="section-title-row"><h2 data-testid="creators-section-title">Seus perfis</h2><span className="count-label" data-testid="filtered-creator-count">{filtered.length}</span></div><span className="subtle-label" data-testid="creators-scope"><ShieldCheck size={14}/>Sessões isoladas</span></div>
    <div className="creator-toolbar"><div className="filter-tabs" role="tablist" aria-label="Situação dos perfis">{[['all', 'Todas'], ['active', 'Em atendimento'], ['paused', 'Pausadas'], ['idle', 'Sem turno']].map(([key, label]) => <button role="tab" aria-selected={filter === key} key={key} data-testid={`creator-filter-${key}`} className={filter === key ? 'selected' : ''} onClick={() => setFilter(key)}>{label}{key === 'all' && <span>{creators.length}</span>}</button>)}</div><div className="toolbar-right"><div className="search-field"><Search size={16}/><input data-testid="creator-search" aria-label="Buscar criadora" placeholder="Buscar criadora..." value={search} onChange={e => setSearch(e.target.value)}/></div><div className="view-toggle"><button data-testid="grid-view" title="Visualização em grade" className={view === 'grid' ? 'selected' : ''} onClick={() => setView('grid')}><LayoutGrid size={16}/></button><button data-testid="list-view" title="Visualização em lista" className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}><List size={18}/></button></div></div></div>
    {filtered.length ? <div className={`creator-grid ${view === 'list' ? 'list-view' : ''}`}>{filtered.map(c => <article className="creator-card" key={c.id} data-testid={`creator-card-${c.id}`}><div className="creator-card-top"><div className={`avatar creator-avatar ${c.color}`}>{initials(c.name)}</div><div className="creator-name"><h3 data-testid={`creator-name-${c.id}`}>{c.name}</h3><span data-testid={`creator-handle-${c.id}`}>{c.handle ? `@${c.handle.replace(/^@/, '')}` : 'Perfil Privacy'}</span></div><button data-testid={`creator-details-${c.id}`} title="Detalhes do perfil" className="icon-btn" onClick={() => { setDetails(c); setError(''); setDeleteReason(''); }}><Ellipsis size={21}/></button></div>
    <div className="creator-status"><Badge testId={`creator-status-${c.id}`} tone={state(c)[1]}>{state(c)[0]}</Badge><span className="platform-label" data-testid={`creator-platform-${c.id}`}>privacy</span></div><div className="creator-data"><div><span>Operador</span><strong data-testid={`creator-operator-${c.id}`}>{c.shift?.operator_name || 'Não atribuído'}</strong></div><div><span>Início do turno</span><strong data-testid={`creator-shift-start-${c.id}`}>{c.shift ? dateTime(c.shift.started_at).split(' ').pop() : '—'}</strong></div></div>
    <div className="creator-observation" data-testid={`creator-observation-${c.id}`}><span className={station?.online && c.browser?.observation_state === 'partial' ? 'online-dot' : 'offline-dot'}/>{observation(c)}</div><div className="creator-card-actions"><Button variant="outline" data-testid={`open-browser-${c.id}`} onClick={() => action(c, 'browser')} disabled={busy}><Monitor size={15}/>Abrir navegador<ArrowUpRight size={14}/></Button>{!c.shift ? <button className="shift-link" data-testid={`start-shift-${c.id}`} onClick={() => action(c, 'start')} disabled={busy}><Play size={13}/>Iniciar turno</button> : (isManager || c.shift.operator_id === user.id) ? <div className="shift-actions"><button title={c.shift.paused ? 'Retomar turno' : 'Pausar turno'} className="shift-link" data-testid={`pause-shift-${c.id}`} onClick={() => action(c, c.shift.paused ? 'resume' : 'pause')} disabled={busy}>{c.shift.paused ? <Play size={13}/> : <Pause size={13}/>} {c.shift.paused ? 'Retomar' : 'Pausar'}</button><button title="Encerrar turno" data-testid={`end-shift-${c.id}`} className="icon-btn" onClick={() => action(c, 'end')} disabled={busy}><Square size={13}/></button></div> : <span className="subtle-label">Turno em andamento</span>}</div></article>)}
      {isManager && view === 'grid' && <button className="add-creator-tile" data-testid="add-creator-tile" onClick={() => openForm()}><span><Plus size={23}/></span><strong>Mais uma criadora,<br/>um novo espaço.</strong><small>Adicionar perfil <ArrowRight size={13}/></small></button>}</div> : <Empty id="creators-empty" icon={Layers3} title={creators.length ? 'Nenhum perfil encontrado' : 'O próximo capítulo começa com uma criadora.'} description={creators.length ? 'Experimente outro nome ou situação de atendimento.' : 'Seus perfis, operadores e turnos vão se encontrar aqui.'}>{isManager && !creators.length && <Button data-testid="add-first-creator" onClick={() => openForm()}><Plus size={16}/>Cadastrar primeira criadora</Button>}</Empty>}
    <div className="list-footer"><span data-testid="creator-list-total">{filtered.length} {filtered.length === 1 ? 'perfil' : 'perfis'} no workspace</span><span data-testid="creator-observation-limit">Acompanhamento somente das telas observadas <span>·</span> Cobertura parcial</span></div></section>
    <Modal open={!!form} onClose={() => setForm(null)} title={form?.id ? 'Editar criadora' : 'Um novo espaço para sua criadora'} description="O login na Privacy será feito diretamente no navegador local." id="creator-form-modal"><form onSubmit={save} className="form-stack"><Field id="creator-name-input" name="name" label="Nome da criadora" placeholder="Ex.: Marina Costa" defaultValue={form?.name} required minLength={2} maxLength={70}/><Field id="creator-handle-input" name="handle" label="Identificador (opcional)" placeholder="nome.na.privacy" defaultValue={form?.handle} maxLength={60}/><div className="field"><span>Cor do perfil</span><div className="color-swatches">{['green', 'rose', 'blue', 'amber', 'lavender'].map(c => <button type="button" aria-label={`Cor ${c}`} data-testid={`color-${c}`} key={c} onClick={() => setColor(c)} className={`color-swatch ${c} ${color === c ? 'selected' : ''}`}/>)}</div></div><FormError error={error}/><div className="form-actions"><Button type="button" data-testid="cancel-creator-form" variant="outline" onClick={() => setForm(null)}>Cancelar</Button><Submit busy={busy} id="save-creator">{form?.id ? 'Salvar alterações' : 'Cadastrar criadora'}</Submit></div></form></Modal>
    <Modal open={!!details} onClose={() => setDetails(null)} title={details?.name} id="creator-details-modal"><Badge testId="creator-detail-coverage">{details ? observation(details) : ''}</Badge><p data-testid="creator-detail-last-seen" className="body-muted">Última comunicação do perfil: {dateTime(details?.browser?.last_seen)}</p><Notice id="creator-detail-notice">Senhas e sessões da Privacy não são armazenadas neste painel.</Notice>{isManager && <><Button variant="outline" data-testid="edit-creator" onClick={() => openForm(details)}><Pencil size={15}/>Editar cadastro</Button><div className="danger-zone"><Field id="delete-creator-reason" label="Motivo para excluir o perfil e seus dados" value={deleteReason} onChange={e => setDeleteReason(e.target.value)} placeholder="Sem dados pessoais ou mensagens" maxLength={200}/><Button variant="destructive" data-testid="delete-creator" disabled={busy || deleteReason.trim().length < 5} onClick={async () => { setBusy(true); try { await api.delete(`/creators/${details.id}`, { data: { reason: deleteReason } }); setDetails(null); await refresh(); toast.success('Perfil e dados excluídos.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }}><Trash2 size={15}/>Excluir perfil</Button><FormError error={error}/></div></>}</Modal>
  </>;
}