import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Plus, Search, LayoutGrid, List, UsersRound, Monitor, Timer, ArrowUpRight, Ellipsis, Play, Pause, Square, Settings2, Layers3, ShieldCheck, Activity, ArrowRight, Pencil, Trash2, KeyRound, IdCard, StickyNote, Eye } from 'lucide-react';
import { CreatorProfileForm } from '../components/CreatorProfileForm';
import { CreatorNotes } from '../components/CreatorNotes';
import { CreatorTrash } from '../components/CreatorTrash';
import { toast } from 'sonner';
import { useApp } from '../App';
import { api, initials, errorText, dateTime } from '../lib/api';
import { PageHeading, Badge, Button, Field, Select, Modal, Submit, FormError, Stat, Notice, Empty, Avatar, shrinkImage } from '../components/Common';
import Credentials from '../components/Credentials';

export default function Creators() {
  const { user, creators, refresh } = useApp(); const [search, setSearch] = useState(''), [filter, setFilter] = useState('all'), [view, setView] = useState('grid');
  const navigate = useNavigate();
  // plataformas de cada criadora = as que têm acesso salvo no cofre (sem nenhum, Privacy)
  const PLAT = { privacy: 'Privacy', fatalfans: 'FatalFans', closefans: 'CloseFans', onlyfans: 'OnlyFans', x: 'X', instagram: 'Instagram', facebook: 'Facebook' };
  const [plats, setPlats] = useState({});
  useEffect(() => { api.get('/credentials').then(r => { const m = {}; for (const c of r.data || []) (m[c.creator_id] = m[c.creator_id] || []).push(c.platform); setPlats(m); }).catch(() => {}); }, [creators.length]);
  const platformsOf = (c) => { const order = Object.keys(PLAT); const list = (plats[c.id] || []).filter(p => ['privacy', 'fatalfans', 'closefans', 'onlyfans'].includes(p)).sort((a, b) => order.indexOf(a) - order.indexOf(b)); return list.length ? list : ['privacy']; };
  const [form, setForm] = useState(null), [color, setColor] = useState('green'), [busy, setBusy] = useState(false), [error, setError] = useState(''), [details, setDetails] = useState(null), [deleteReason, setDeleteReason] = useState(''), [vault, setVault] = useState(null), [persona, setPersona] = useState(null), [notesOf, setNotesOf] = useState(null), [trashKey, setTrashKey] = useState(0);
  const isManager = user.role === 'manager', active = creators.filter(c => c.shift && !c.shift.paused).length;
  const filtered = creators.filter(c => `${c.name} ${c.handle}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || filter === 'active' && c.shift && !c.shift.paused || filter === 'paused' && c.shift?.paused || filter === 'idle' && !c.shift));
  async function pickCreatorPhoto(c, e) { const file = e.target.files?.[0]; e.target.value = ''; if (!file) return; try { const image = await shrinkImage(file); await api.put(`/creators/${c.id}/avatar`, { image }); await refresh(); toast.success('Foto da criadora atualizada.'); } catch (err) { toast.error(err.response ? errorText(err) : err.message); } }
  const openForm = (c = {}) => { setForm(c); setColor(c.color || 'green'); setError(''); setDetails(null); };
  async function save(e) { e.preventDefault(); setBusy(true); setError(''); const body = { ...Object.fromEntries(new FormData(e.currentTarget)), color };
    try { await (form.id ? api.patch(`/creators/${form.id}`, body) : api.post('/creators', body)); await refresh(); setForm(null); toast.success(form.id ? 'Cadastro atualizado.' : 'Criadora cadastrada.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); }
  }
  async function action(c, type) { setBusy(true); try {
    if (type === 'browser') { navigate('/instalar'); }
    else if (type === 'start') { await api.post('/shifts', { creator_id: c.id }); toast.success('Seu turno começou.'); }
    else { await api.post(`/shifts/${c.shift.id}/action`, { action: type }); toast.success(type === 'end' ? 'Turno encerrado.' : type === 'pause' ? 'Atendimento pausado.' : 'Atendimento retomado.'); }
    await refresh();
  } catch (e) { toast.error(errorText(e)); } finally { setBusy(false); } }
  const state = c => c.review ? ['Em revisão', 'amber'] : c.shift?.paused ? ['Pausado', 'amber'] : c.shift ? ['Em atendimento', 'green'] : ['Sem turno ativo', 'neutral'];
  const observation = c => {
    const fresh = c.browser && c.browser.state === 'open';
    if (!fresh) return 'App fechado · sem presença';
    const via = c.browser?.source === 'desktop' ? 'Alta Pulse desktop' : 'Extensão Chrome';
    return ({ partial: 'Atendendo · na conversa', validation_required: 'Na conversa · leitura pendente', paused: 'Turno pausado', no_data: 'Privacy aberta · fora do chat', interrupted: 'Presença interrompida' }[c.browser?.observation_state] || 'Privacy aberta') + ' · ' + via;
  };
  return <><PageHeading title="Criadoras" description="Cada perfil no seu espaço. Toda a operação à vista."><span className="heading-date" data-testid="today-date">{new Intl.DateTimeFormat('pt-BR', { day: 'numeric', month: 'long', timeZone: 'America/Sao_Paulo' }).format(new Date())}</span>{isManager && <Button data-testid="add-creator-button" onClick={() => openForm()}><Plus size={17}/>Nova criadora</Button>}</PageHeading>
    <div className="stats-grid"><Stat id="creators-total" label="Criadoras cadastradas" value={creators.length.toString().padStart(2, '0')} caption="Perfis independentes" icon={UsersRound}/><Stat id="creators-active" label="Em atendimento" value={active.toString().padStart(2, '0')} caption="Com turno ativo agora" icon={Activity} tone="green"/><Stat id="creators-browsers" label="Presença na Privacy" value={creators.filter(c => c.browser?.state === 'open').length.toString().padStart(2, '0')} caption="App ou extensão ativos agora" icon={Monitor}/><Stat id="creators-waiting" label="Aguardando turno" value={creators.filter(c => !c.shift).length.toString().padStart(2, '0')} caption="Sem operador responsável" icon={Timer}/></div>
    <div className="connection-banner" data-testid="station-connection-banner"><div className="connection-icon"><Monitor size={22}/></div><div><strong data-testid="connection-banner-title">O atendimento acontece no Alta Pulse desktop de cada chatter.</strong><p data-testid="connection-banner-description">Instale o app para abrir cada criadora num perfil isolado e acompanhar presença, turnos, fila, tempo de resposta e vendas. A extensão do Chrome continua disponível.</p></div><Link to="/instalar" data-testid="setup-station-link">Instalar o app<ArrowUpRight size={16}/></Link></div>
    <section className="creator-section"><div className="section-heading"><div className="section-title-row"><h2 data-testid="creators-section-title">Seus perfis</h2><span className="count-label" data-testid="filtered-creator-count">{filtered.length}</span></div><span className="subtle-label" data-testid="creators-scope"><ShieldCheck size={14}/>Sessões isoladas</span></div>
    <div className="creator-toolbar"><div className="filter-tabs" role="tablist" aria-label="Situação dos perfis">{[['all', 'Todas'], ['active', 'Em atendimento'], ['paused', 'Pausadas'], ['idle', 'Sem turno']].map(([key, label]) => <button role="tab" aria-selected={filter === key} key={key} data-testid={`creator-filter-${key}`} className={filter === key ? 'selected' : ''} onClick={() => setFilter(key)}>{label}{key === 'all' && <span>{creators.length}</span>}</button>)}</div><div className="toolbar-right"><div className="search-field"><Search size={16}/><input data-testid="creator-search" aria-label="Buscar criadora" placeholder="Buscar criadora..." value={search} onChange={e => setSearch(e.target.value)}/></div><div className="view-toggle"><button data-testid="grid-view" title="Visualização em grade" className={view === 'grid' ? 'selected' : ''} onClick={() => setView('grid')}><LayoutGrid size={16}/></button><button data-testid="list-view" title="Visualização em lista" className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}><List size={18}/></button></div></div></div>
    {filtered.length ? <div className={`creator-grid ${view === 'list' ? 'list-view' : ''}`}>{filtered.map(c => <article className="creator-card" key={c.id} data-testid={`creator-card-${c.id}`}><div className="creator-card-top">{isManager ? <label className={`avatar creator-avatar ${c.color} creator-photo-pick`} title={c.avatar ? 'Trocar a foto da criadora' : 'Colocar a foto da criadora'} data-testid={`creator-photo-${c.id}`}>{c.avatar ? <img src={c.avatar} alt=""/> : initials(c.name)}<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e => pickCreatorPhoto(c, e)}/></label> : <div className={`avatar creator-avatar ${c.color}`}>{c.avatar ? <img src={c.avatar} alt=""/> : initials(c.name)}</div>}<div className="creator-name"><h3 data-testid={`creator-name-${c.id}`}>{c.name}</h3><span data-testid={`creator-handle-${c.id}`}>{c.handle ? `@${c.handle.replace(/^@/, '')}` : platformsOf(c).map(p => PLAT[p]).join(' · ')}</span></div>{isManager && <button data-testid={`creator-profile-${c.id}`} title="Ficha da criadora (persona e preços para a Alta Ajuda)" className="icon-btn" onClick={() => setPersona(c)}><IdCard size={17}/></button>}<button data-testid={`creator-notes-${c.id}`} title={c.notes_info ? `${c.notes_info.count} anotaç${c.notes_info.count === 1 ? 'ão' : 'ões'} · última: ${c.notes_info.last.text}` : 'Anotações da criadora'} className={`icon-btn ${c.notes_info ? 'has-notes' : ''}`} onClick={() => setNotesOf(c)}><StickyNote size={17}/>{c.notes_info ? <i className="notes-count">{c.notes_info.count}</i> : null}</button><button data-testid={`creator-vault-${c.id}`} title="Acessos das plataformas (cofre)" className="icon-btn" onClick={() => setVault(c)}><KeyRound size={17}/></button><button data-testid={`creator-details-${c.id}`} title="Detalhes do perfil" className="icon-btn" onClick={() => { setDetails(c); setError(''); setDeleteReason(''); }}><Ellipsis size={21}/></button></div>
    <div className="creator-status"><Badge testId={`creator-status-${c.id}`} tone={state(c)[1]}>{state(c)[0]}</Badge><span className="platform-label" data-testid={`creator-platform-${c.id}`}>{platformsOf(c).join(' · ')}</span></div><div className="creator-data"><div><span>Operador</span><strong data-testid={`creator-operator-${c.id}`} className="operator-with-photo">{c.shift && <Avatar name={c.shift.operator_name} src={c.shift.operator_avatar} className="tiny-avatar"/>}{c.shift?.operator_name || 'Não atribuído'}</strong></div><div><span>Início do turno</span><strong data-testid={`creator-shift-start-${c.id}`}>{c.shift ? dateTime(c.shift.started_at).split(' ').pop() : '—'}</strong></div></div>
    {(c.group || c.tag) && <div className="creator-meta" data-testid={`creator-meta-${c.id}`}>{(c.groups?.length ? c.groups : (c.group ? [c.group] : [])).map(g => <span key={g} className="meta-chip">{g}</span>)}{c.tag && <span className="meta-chip tag">{c.tag}</span>}</div>}<div className="creator-observation" data-testid={`creator-observation-${c.id}`}><span className={c.browser?.state === 'open' ? 'online-dot' : 'offline-dot'}/>{observation(c)}</div>{c.viewers?.length > 0 && <div className="creator-viewers" data-testid={`creator-viewers-${c.id}`}><Eye size={13}/>{c.viewers.map(v => <Avatar key={v.id} name={v.name} src={v.avatar} className="tiny-avatar"/>)}<span>{c.viewers.map(v => v.name.split(' ')[0]).join(', ')} {c.viewers.length === 1 ? 'está' : 'estão'} neste perfil agora</span></div>}<div className="creator-card-actions"><Button variant="outline" data-testid={`open-browser-${c.id}`} onClick={() => action(c, 'browser')} disabled={busy}><Monitor size={15}/>Abrir no app<ArrowUpRight size={14}/></Button>{!c.shift ? <button className="shift-link" data-testid={`start-shift-${c.id}`} onClick={() => action(c, 'start')} disabled={busy}><Play size={13}/>Iniciar turno</button> : (isManager || c.shift.operator_id === user.id) ? <div className="shift-actions"><button title={c.shift.paused ? 'Retomar turno' : 'Pausar turno'} className="shift-link" data-testid={`pause-shift-${c.id}`} onClick={() => action(c, c.shift.paused ? 'resume' : 'pause')} disabled={busy}>{c.shift.paused ? <Play size={13}/> : <Pause size={13}/>} {c.shift.paused ? 'Retomar' : 'Pausar'}</button><button title="Encerrar turno" data-testid={`end-shift-${c.id}`} className="icon-btn" onClick={() => action(c, 'end')} disabled={busy}><Square size={13}/></button></div> : <span className="subtle-label">Turno em andamento</span>}</div></article>)}
      {isManager && view === 'grid' && <button className="add-creator-tile" data-testid="add-creator-tile" onClick={() => openForm()}><span><Plus size={23}/></span><strong>Mais uma criadora,<br/>um novo espaço.</strong><small>Adicionar perfil <ArrowRight size={13}/></small></button>}</div> : <Empty id="creators-empty" icon={Layers3} title={creators.length ? 'Nenhum perfil encontrado' : 'O próximo capítulo começa com uma criadora.'} description={creators.length ? 'Experimente outro nome ou situação de atendimento.' : 'Seus perfis, operadores e turnos vão se encontrar aqui.'}>{isManager && !creators.length && <Button data-testid="add-first-creator" onClick={() => openForm()}><Plus size={16}/>Cadastrar primeira criadora</Button>}</Empty>}
    <div className="list-footer"><span data-testid="creator-list-total">{filtered.length} {filtered.length === 1 ? 'perfil' : 'perfis'} no workspace</span><span data-testid="creator-observation-limit">Acompanhamento somente das telas observadas <span>·</span> Cobertura parcial</span></div></section>
    {isManager && <CreatorTrash reloadKey={trashKey} onRestored={refresh}/>}
    <Modal open={!!form} onClose={() => setForm(null)} title={form?.id ? 'Editar criadora' : 'Um novo espaço para sua criadora'} description="O login na Privacy será feito diretamente no navegador local." id="creator-form-modal"><form onSubmit={save} className="form-stack"><Field id="creator-name-input" name="name" label="Nome da criadora" placeholder="Ex.: Marina Costa" defaultValue={form?.name} required minLength={2} maxLength={70}/><Field id="creator-handle-input" name="handle" label="Identificador (opcional)" placeholder="nome.na.privacy" defaultValue={form?.handle} maxLength={60}/><div className="field"><span>Cor do perfil</span><div className="color-swatches">{['green', 'rose', 'blue', 'amber', 'lavender'].map(c => <button type="button" aria-label={`Cor ${c}`} data-testid={`color-${c}`} key={c} onClick={() => setColor(c)} className={`color-swatch ${c} ${color === c ? 'selected' : ''}`}/>)}</div></div><FormError error={error}/><div className="form-actions"><Button type="button" data-testid="cancel-creator-form" variant="outline" onClick={() => setForm(null)}>Cancelar</Button><Submit busy={busy} id="save-creator">{form?.id ? 'Salvar alterações' : 'Cadastrar criadora'}</Submit></div></form></Modal>
    <Modal open={!!details} onClose={() => setDetails(null)} title={details?.name} id="creator-details-modal"><Badge testId="creator-detail-coverage">{details ? observation(details) : ''}</Badge><p data-testid="creator-detail-last-seen" className="body-muted">Última comunicação do perfil: {dateTime(details?.browser?.last_seen)}</p><Notice id="creator-detail-notice">As sessões das plataformas ficam só no computador do chatter. Logins e senhas, quando cadastrados pelo gestor, ficam criptografados no cofre (ícone de chave no card).</Notice>{isManager && <><Button variant="outline" data-testid="edit-creator" onClick={() => openForm(details)}><Pencil size={15}/>Editar cadastro</Button><div className="danger-zone"><Field id="delete-creator-reason" label="Motivo para excluir (vai para Apagados recentemente por 30 dias)" value={deleteReason} onChange={e => setDeleteReason(e.target.value)} placeholder="Sem dados pessoais ou mensagens" maxLength={200}/><Button variant="destructive" data-testid="delete-creator" disabled={busy || deleteReason.trim().length < 5} onClick={async () => { setBusy(true); try { await api.delete(`/creators/${details.id}`, { data: { reason: deleteReason } }); setDetails(null); await refresh(); setTrashKey(k => k + 1); toast.success('Criadora enviada para Apagados recentemente. Dá para restaurar por 30 dias.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }}><Trash2 size={15}/>Excluir perfil</Button><FormError error={error}/></div></>}</Modal>
    <Modal wide open={!!persona} onClose={() => setPersona(null)} title={persona ? `Ficha · ${persona.name}` : ''} description="Persona, limites e tabela de preços. Alimenta a Alta Ajuda e a consulta do chatter no app. Campo vazio fica em aberto." id="creator-profile-modal">{persona && <CreatorProfileForm creatorId={persona.id}/>}</Modal>
    <Modal open={!!notesOf} onClose={() => { setNotesOf(null); refresh(); }} title={notesOf ? `Anotações · ${notesOf.name}` : ''} description="Recados para a equipe sobre esta criadora: aparecem aqui e no app, com quem escreveu e quando." id="creator-notes-modal">{notesOf && <CreatorNotes creator={notesOf} user={user}/>}</Modal>
    <Modal wide open={!!vault} onClose={() => setVault(null)} title={vault ? `Acessos · ${vault.name}` : ''} description="Cofre de logins e senhas das plataformas desta criadora." id="creator-vault-modal">{vault && <Credentials creator={vault} isManager={isManager}/>}</Modal>
  </>;
}