import React, { useState, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import { Monitor, Check, Ban, Download, RefreshCw, ArrowRight, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { useApp } from '../App';
import { api, errorText, dateTime } from '../lib/api';
import { Badge, Button, PageHeading, Empty, Notice, Modal } from '../components/Common';
import { DesktopDownload } from '../components/DesktopDownload';

export const DesktopSettings = () => <><div className="desktop-settings-intro"><div className="station-device"><Monitor size={34}/></div><div><span className="eyebrow">ALTA PULSE DESKTOP</span><h2 data-testid="desktop-settings-title">Uma instalação para cada computador.</h2><p data-testid="desktop-settings-description">Gestores e chatters usam o mesmo aplicativo, com permissões individuais.</p></div><DesktopDownload id="settings-download-desktop" compact/></div><div className="desktop-settings-links"><Link to="/computadores" data-testid="manage-desktop-devices"><ShieldCheck size={20}/><span><strong>Computadores da equipe</strong><small>Aprove novos acessos e revogue instalações.</small></span><ArrowRight size={17}/></Link><Link to="/baixar" data-testid="desktop-install-instructions"><Download size={20}/><span><strong>Instalação e requisitos</strong><small>Windows 64 bits · sem Python.</small></span><ArrowRight size={17}/></Link></div><Notice id="desktop-session-boundary">Os perfis e as permissões aparecem em todas as instalações autorizadas. O login da Privacy precisa ser feito em cada computador; login único entre máquinas ainda não está disponível.</Notice><Notice id="desktop-validation-boundary" tone="amber">Instalador sem assinatura digital. A compatibilidade real com a Privacy ainda depende de validação no Windows. O navegador integrado não ativa coleta automática de mensagens ou métricas.</Notice></>;

export default function DesktopDevices() {
  const { user, isDesktop, desktopDevice } = useApp(); const [devices, setDevices] = useState([]), [error, setError] = useState(''), [confirm, setConfirm] = useState(null), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setDevices((await api.get('/desktop/devices')).data); setError(''); } catch (e) { setError(errorText(e)); } }, []);
  useEffect(() => { load(); const id = setInterval(load, 15000); return () => clearInterval(id); }, [load]);
  const action = async () => { setBusy(true); try { await api.post(`/desktop/devices/${confirm.id}/action`, { action: confirm.action }); await load(); setConfirm(null); toast.success('Permissão do computador atualizada.'); } catch (e) { toast.error(errorText(e)); } finally { setBusy(false); } };
  return <><PageHeading eyebrow="ACESSOS DA EQUIPE" title="Computadores" description="Cada pessoa tem seu acesso. Cada computador, sua autorização."><Button variant="outline" data-testid="refresh-devices" onClick={load}><RefreshCw size={16}/>Atualizar</Button><DesktopDownload id="devices-download-desktop" compact/></PageHeading>{error && <Notice id="devices-error" tone="danger">{error}</Notice>}{isDesktop && desktopDevice && <Notice id="current-desktop-device">Este computador: {desktopDevice.name} · {desktopDevice.status === 'approved' ? 'Autorizado' : desktopDevice.status === 'pending' ? 'Aguardando aprovação' : 'Acesso revogado'}</Notice>}
    <section className="data-section"><div className="section-heading"><h2 data-testid="devices-section-title">{user.role === 'manager' ? 'Instalações da agência' : 'Meus computadores'}</h2><span className="count-label" data-testid="devices-count">{devices.length}</span></div>{devices.length ? <div className="table-scroll"><table><thead><tr><th>Computador</th><th>Responsável</th><th>Versão</th><th>Último acesso</th><th>Situação</th>{user.role === 'manager' && <th>Ações</th>}</tr></thead><tbody>{devices.map(d => <tr key={d.id} data-testid={`device-row-${d.id}`}><td><strong>{d.name}</strong></td><td>{d.user_name}</td><td>{d.version}</td><td>{dateTime(d.last_seen)}</td><td><Badge testId={`device-status-${d.id}`} tone={d.status === 'approved' ? 'green' : d.status === 'pending' ? 'amber' : 'red'}>{d.status === 'approved' ? 'Autorizado' : d.status === 'pending' ? 'Aguardando aprovação' : 'Revogado'}</Badge></td>{user.role === 'manager' && <td><Button variant="ghost" data-testid={`device-action-${d.id}`} onClick={() => setConfirm({ ...d, action: d.status === 'approved' ? 'revoke' : 'approve' })}>{d.status === 'approved' ? <Ban size={14}/> : <Check size={14}/>} {d.status === 'approved' ? 'Revogar' : 'Autorizar'}</Button></td>}</tr>)}</tbody></table></div> : <Empty id="devices-empty" icon={Monitor} title="Os computadores da equipe aparecerão aqui." description="Instale o Alta Pulse e entre com seu acesso. Computadores de chatters aguardam aprovação de um gestor."/>}</section><Notice id="device-revocation-note">Revogar um computador encerra a autorização do navegador em até 10 segundos com conexão ativa. Não apaga nem transfere a sessão local da Privacy.</Notice><Modal id="device-action-modal" open={!!confirm} onClose={() => setConfirm(null)} title={confirm?.action === 'approve' ? 'Autorizar este computador?' : 'Revogar acesso deste computador?'} description={`${confirm?.name || ''} · ${confirm?.user_name || ''}`}><p className="body-muted" data-testid="device-action-description">{confirm?.action === 'approve' ? 'O integrante poderá abrir somente as criadoras que já estão autorizadas em seu cadastro.' : 'O navegador integrado será fechado na próxima verificação. O cadastro e as permissões de criadoras não serão apagados.'}</p><div className="form-actions"><Button variant="outline" data-testid="cancel-device-action" onClick={() => setConfirm(null)}>Cancelar</Button><Button data-testid="confirm-device-action" disabled={busy} onClick={action}>Confirmar</Button></div></Modal></>;
}