import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, Monitor, ShieldCheck, KeyRound, UsersRound, Check, Info, ExternalLink } from 'lucide-react';
import { Brand, BrandMark } from '../components/Brand';
import { DesktopDownload, useDesktopRelease } from '../components/DesktopDownload';
import { useApp } from '../App';

export default function DownloadDesktop() {
  const { user } = useApp(); const { release } = useDesktopRelease();
  return <div className="desktop-download-page"><header className="download-page-header"><Link data-testid="download-brand-home" to="/"><Brand/></Link><Link className="download-back" data-testid="download-back" to="/"><ArrowLeft size={15}/>{user ? 'Voltar ao painel' : 'Entrar no Alta Core'}</Link></header>
    <main className="download-page-main"><div className="download-intro"><span className="eyebrow" data-testid="download-eyebrow">ALTA CORE PARA WINDOWS</span><h1 data-testid="download-title">Sua operação.<br/><span>Na mesma janela.</span></h1><p data-testid="download-subtitle">Criadoras na lateral. Navegadores separados.<br/>Um lugar para sua equipe atender.</p><DesktopDownload id="download-windows-installer"/><div className="download-trust" data-testid="download-trust"><ShieldCheck size={15}/>Sessões locais · Acesso individual · Sem API da Privacy</div></div>
    <div className="desktop-product-visual" aria-hidden="true"><div className="visual-window-bar"><BrandMark/><span>Alta Core</span><i/><i/></div><div className="visual-window-content"><div className="visual-sidebar"><span>PERFIS DA EQUIPE</span><div className="visual-profile active"><div/><i/><Monitor size={12}/></div><div className="visual-profile"><div/><i/></div><div className="visual-profile"><div/><i/></div><div className="visual-profile"><div/><i/></div></div><div className="visual-browser"><div className="visual-url"><ShieldCheck size={11}/><span>Navegador da criadora</span></div><div className="visual-browser-body"><BrandMark/><span>Um perfil.<br/>Uma sessão isolada.</span></div></div></div><span className="visual-caption" data-testid="desktop-illustration-label">Organização do aplicativo · não é uma sessão conectada</span></div>
    <section className="download-steps"><div><span>01</span><h2>Instale e entre</h2><p>Abra o instalador no Windows e entre com seu acesso pessoal ao Alta Core. Não precisa instalar Python.</p></div><div><span>02</span><h2>Autorize o computador</h2><p>Você e a Fernanda podem ter contas de gestor. O gestor aprova os computadores dos chatters e define suas criadoras.</p></div><div><span>03</span><h2>Abra a criadora</h2><p>Selecione o perfil na lateral. O primeiro login na Privacy é feito diretamente no navegador desse computador.</p></div></section>
    <section className="download-boundaries"><div><Info size={19}/><div><h2 data-testid="local-login-title">Cada computador tem sua própria sessão</h2><p data-testid="local-login-note">Cadastros e permissões são compartilhados pelo painel. O login da Privacy não é copiado entre máquinas. A liberação com login único para vários computadores não está disponível nesta versão.</p></div></div><div><ShieldCheck size={19}/><div><h2 data-testid="unsigned-title">Primeira versão · instalador sem assinatura digital</h2><p data-testid="unsigned-note">O Windows pode exibir um aviso de segurança. Não desative as proteções do computador. A instalação, o login e a compatibilidade com a Privacy ainda precisam ser verificados numa estação Windows autorizada.</p></div></div><div><Monitor size={19}/><div><h2 data-testid="desktop-observation-title">Atendimento manual, sem coleta automática</h2><p data-testid="desktop-observation-note">Este aplicativo abre o navegador integrado. Os indicadores de leitura da Privacy continuam indisponíveis até uma validação específica; nenhum dado de conversa é enviado ao painel por este navegador.</p></div></div></section>
    {release?.available && <div className="release-details" data-testid="release-details"><span data-testid="release-version">Versão {release.version} · Windows x64</span><details data-testid="release-checksum-details"><summary data-testid="show-checksum">Verificar integridade do instalador</summary><code data-testid="release-checksum">SHA-256: {release.sha256}</code></details></div>}
    </main><footer className="download-page-footer"><span>Alta Core · Um produto Alta Agency.</span><span>Seu acesso ao painel permanece o mesmo.</span></footer></div>;
}