import React, { useEffect, useState } from 'react';
import { Users, Crown, UserMinus, Sparkles, Search, RefreshCw, AlertTriangle } from 'lucide-react';
import { toast } from 'sonner';
import { useApp } from '../App';
import { api, money, errorText, dateTime, initials } from '../lib/api';
import { PageHeading, Stat, Button, Empty, Notice, Badge, Select } from '../components/Common';

// Bloco D: CRM de assinantes montado pelas vendas do extrato (nome de exibição quando a opção está ligada).
const SEG = { vip: ['VIP', 'green'], ativo: ['Ativo', 'neutral'], novo: ['Novo', 'green'], sumiu: ['Sumiu', 'amber'], so_ofertas: ['Só ofertas', 'neutral'], sem_compra: ['Assina, nunca comprou', 'neutral'], inativo: ['Assinatura inativa', 'amber'] };
const PROD = { chat: 'chat', subscription: 'assinatura', renewal: 'renovação', post: 'publicação', tip: 'mimo' };
export default function Fans() {
  const { creators } = useApp();
  const [data, setData] = useState(null), [creator, setCreator] = useState(''), [days, setDays] = useState(90), [segment, setSegment] = useState('all'), [search, setSearch] = useState(''), [busy, setBusy] = useState(false);
  const load = async () => { setBusy(true); try { const r = await api.get('/fans', { params: { creator_id: creator || undefined, days } }); setData(r.data); } catch (e) { toast.error(errorText(e)); } finally { setBusy(false); } };
  useEffect(() => { load(); }, [creator, days]);
  const rows = (data?.fans || []).filter(f => (segment === 'all' || f.segment === segment || (segment === 'risco' && f.churn_risk)) && (!search || (f.fan_name || '').toLowerCase().includes(search.toLowerCase())));
  const seg = data?.segments || {};
  return <><PageHeading eyebrow="QUEM COMPRA" title="Assinantes" description="Quem mais compra, quem sumiu e quem chegou agora, por criadora. Montado pelas vendas do extrato e pela lista de assinantes do Meu Privacy."><Select id="fans-creator" value={creator} onChange={e => setCreator(e.target.value)}><option value="">Todas as criadoras</option>{creators.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select id="fans-days" value={days} onChange={e => setDays(+e.target.value)}><option value={30}>30 dias</option><option value={90}>90 dias</option><option value={180}>180 dias</option><option value={365}>1 ano</option></Select><Button variant="outline" data-testid="fans-reload" onClick={load} disabled={busy}><RefreshCw size={15}/>Atualizar</Button></PageHeading>
    <div className="stats-grid"><Stat id="fans-total" label="Assinantes com compra" value={data?.count ?? '—'} caption={`Nos últimos ${days} dias · ${money(data?.total_cents)}`} icon={Users}/><Stat id="fans-vip" label="VIP (R$ 300+)" value={seg.vip || 0} caption="Gasto total no período" icon={Crown} tone="green"/><Stat id="fans-gone" label="Sumiram" value={seg.sumiu || 0} caption="Compraram, mas nada há 30 dias" icon={UserMinus} tone="amber"/><Stat id="fans-new" label="Novos" value={seg.novo || 0} caption="Primeira compra nos últimos 7 dias" icon={Sparkles}/><Stat id="fans-risk" label="Em risco" value={seg.risco || 0} caption="Já compraram e a assinatura está inativa" icon={AlertTriangle} tone="amber"/></div>
    {data && !data.fan_names_allowed && <Notice id="fans-names-notice" tone="amber">A opção "guardar nome do assinante" está desligada em Configurações: os assinantes aparecem sem nome.</Notice>}
    <div className="creator-toolbar"><div className="filter-tabs">{[['all', 'Todos'], ['vip', 'VIP'], ['ativo', 'Ativos'], ['novo', 'Novos'], ['sumiu', 'Sumiram'], ['risco', 'Risco (assinatura inativa)'], ['sem_compra', 'Assinam, nunca compraram'], ['so_ofertas', 'Só ofertas']].map(([k, l]) => <button key={k} className={segment === k ? 'selected' : ''} onClick={() => setSegment(k)}>{l}{seg[k] ? <span>{seg[k]}</span> : null}</button>)}</div><div className="toolbar-right"><div className="search-field"><Search size={16}/><input placeholder="Buscar assinante..." value={search} onChange={e => setSearch(e.target.value)}/></div></div></div>
    {rows.length ? <section className="data-section"><div className="table-scroll"><table><thead><tr><th>Assinante</th><th>Criadora</th><th>Situação</th><th>Assinatura</th><th>Gasto total</th><th>Compras</th><th>Ticket</th><th>Chat</th><th>Assinatura</th><th>Publicações</th><th>Ofertas</th><th>Última compra</th><th>Pagamento</th></tr></thead><tbody>
      {rows.map(f => <tr key={f.creator_id + f.fan_ref}><td><div className="person-cell"><span className="avatar small-avatar">{initials(f.fan_name || '?')}</span><div><strong>{f.fan_name || 'Sem nome'}</strong><span>desde {f.first_at ? dateTime(f.first_at).split(' ')[0] : '—'}</span></div></div></td><td>{f.creator_name}</td><td><Badge tone={SEG[f.segment]?.[1]}>{SEG[f.segment]?.[0]}</Badge>{f.churn_risk ? <span className="inherited-label">risco de perder</span> : null}</td><td>{f.sub_status ? <><Badge tone={f.sub_active ? 'green' : f.sub_active === false ? 'amber' : 'neutral'}>{f.sub_status}</Badge><span className="inherited-label">{f.sub_price_cents != null ? money(f.sub_price_cents) : ''}{f.sub_duration ? ` · ${f.sub_duration}` : ''}</span></> : '—'}</td><td className="tabular"><strong>{money(f.total_cents)}</strong>{f.refunded_cents ? <span className="inherited-label">estornos {money(f.refunded_cents)}</span> : null}</td><td>{f.purchases}</td><td className="tabular">{money(f.ticket_cents)}</td><td className="tabular">{money(f.chat_cents)}</td><td className="tabular">{money(f.subscription_cents)}</td><td className="tabular">{money(f.post_cents)}</td><td>{f.offers_sent ? `${f.offers_paid}/${f.offers_sent}` : '—'}</td><td>{f.last_at ? <>{dateTime(f.last_at)}<span className="inherited-label">{f.days_since_last === 0 ? 'hoje' : `há ${f.days_since_last} dias`} · {PROD[f.last_product] || ''}</span></> : '—'}</td><td>{Object.entries(f.payment_methods).sort((a, b) => b[1] - a[1]).map(([k]) => k).join(', ') || '—'}</td></tr>)}
    </tbody></table></div></section> : <Empty id="fans-empty" icon={Users} title="Nenhum assinante no filtro" description="As compras entram pelo extrato lido no app desktop; ofertas entram quando a conversa está aberta."/>}
    <Notice id="fans-notice">Segmentos: VIP = R$ 300+ no período; Novo = primeira compra em 7 dias; Sumiu = comprou, mas nada há 30 dias. Só nome de exibição, valores e datas. Nada de mensagem.</Notice></>;
}
