import React, { useEffect, useState } from 'react';
import { Users, Crown, UserMinus, Sparkles, Search, RefreshCw, AlertTriangle, Snowflake, ListChecks, StickyNote, Trash2, Send } from 'lucide-react';
import { toast } from 'sonner';
import { useApp } from '../App';
import { api, money, errorText, dateTime, initials } from '../lib/api';
import { PageHeading, Stat, Button, Empty, Notice, Badge, Select, Modal } from '../components/Common';

// CRM de assinantes: extrato (compras) + lista de assinantes do Meu Privacy + anotações da equipe.
// Faixas relativas por criadora (top 5% baleias, próximos 15% spenders) e listas de trabalho para os chatters.
const TIER = { baleia: ['Baleia', 'gold'], spender: ['Spender', 'green'], comum: ['Comum', 'neutral'] };
const TAG = { esfriando: ['Esfriando', 'amber'], dormente: ['Dormente', 'neutral'], novo_sem_compra: ['Novo sem compra', 'green'], assinatura_inativa: ['Assinatura inativa', 'red'] };
const PROD = { chat: 'chat', subscription: 'assinatura', renewal: 'renovação', post: 'publicação', tip: 'mimo' };
const FILTERS = [['all', 'Todos'], ['baleia', 'Baleias'], ['spender', 'Spenders'], ['esfriando', 'Esfriando'], ['novo_sem_compra', 'Novos sem compra'], ['dormente', 'Dormentes'], ['risco', 'Assinatura inativa'], ['sem_compra', 'Assinam, nunca compraram']];
const matches = (f, k) => k === 'all' || f.tier === k || (f.tags || []).includes(k) || (k === 'risco' && f.churn_risk) || f.segment === k;

export default function Fans() {
  const { creators } = useApp();
  const [data, setData] = useState(null), [creator, setCreator] = useState(''), [days, setDays] = useState(90), [filter, setFilter] = useState('all'), [search, setSearch] = useState(''), [busy, setBusy] = useState(false);
  const [picked, setPicked] = useState({}), [users, setUsers] = useState([]), [assignee, setAssignee] = useState(''), [tasks, setTasks] = useState([]), [notesFor, setNotesFor] = useState(null), [card, setCard] = useState(null), [noteText, setNoteText] = useState('');
  const load = async () => { setBusy(true); try { const [r, t] = await Promise.all([api.get('/fans', { params: { creator_id: creator || undefined, days } }), api.get('/fan-tasks').catch(() => ({ data: [] }))]); setData(r.data); setTasks(t.data); setPicked({}); } catch (e) { toast.error(errorText(e)); } finally { setBusy(false); } };
  useEffect(() => { load(); }, [creator, days]);
  useEffect(() => { api.get('/users').then(r => setUsers(r.data.filter(u => u.active))).catch(() => {}); }, []);
  const rows = (data?.fans || []).filter(f => matches(f, filter) && (!search || (f.fan_name || '').toLowerCase().includes(search.toLowerCase())));
  const seg = data?.segments || {};
  const count = (k) => k === 'all' ? (data?.fans || []).length : (data?.fans || []).filter(f => matches(f, k)).length;
  const pickedRows = rows.filter(f => picked[f.creator_id + f.fan_ref]);
  const pickedCreators = [...new Set(pickedRows.map(f => f.creator_id))];
  async function assign() {
    if (!assignee) return toast.error('Escolha o chatter.');
    if (pickedCreators.length !== 1) return toast.error('Selecione fãs de uma criadora por vez.');
    try { const r = await api.post('/fan-tasks', { creator_id: pickedCreators[0], fan_refs: pickedRows.map(f => f.fan_ref), assigned_to: assignee, reason: FILTERS.find(x => x[0] === filter)?.[1] || '' }); toast.success(`${r.data.created} fãs enviados para a lista do chatter.`); load(); } catch (e) { toast.error(errorText(e)); }
  }
  async function openNotes(f) { setNotesFor(f); setCard(null); setNoteText(''); try { setCard((await api.get('/fans/card', { params: { creator_id: f.creator_id, fan_ref: f.fan_ref } })).data); } catch (e) { toast.error(errorText(e)); } }
  async function addNote(e) { e.preventDefault(); if (!noteText.trim()) return; try { await api.post('/fans/notes', { creator_id: notesFor.creator_id, fan_ref: notesFor.fan_ref, text: noteText.trim() }); setNoteText(''); openNotes(notesFor); } catch (err) { toast.error(errorText(err)); } }
  async function delNote(id) { try { await api.delete(`/fans/notes/${id}`); openNotes(notesFor); } catch (err) { toast.error(errorText(err)); } }
  const open = tasks.filter(t => t.status === 'open').length, contacted = tasks.filter(t => t.status === 'contacted'), won = contacted.filter(t => t.converted_cents > 0);
  return <><PageHeading eyebrow="QUEM COMPRA" title="Assinantes" description="Quem mais compra, quem está esfriando e quem chegou agora, por criadora. Selecione fãs e mande para a lista de trabalho de um chatter."><Select id="fans-creator" value={creator} onChange={e => setCreator(e.target.value)}><option value="">Todas as criadoras</option>{creators.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select id="fans-days" value={days} onChange={e => setDays(+e.target.value)}><option value={30}>30 dias</option><option value={90}>90 dias</option><option value={180}>180 dias</option><option value={365}>1 ano</option></Select><Button variant="outline" data-testid="fans-reload" onClick={load} disabled={busy}><RefreshCw size={15}/>Atualizar</Button></PageHeading>
    <div className="stats-grid fans-stats"><Stat id="fans-total" label="Fãs com compra" value={data ? (data.fans || []).filter(f => f.purchases).length : '—'} caption={`${days} dias · ${money(data?.total_cents)}`} icon={Users}/><Stat id="fans-whales" label="Baleias (top 5%)" value={seg.baleia || 0} caption="Maiores compradores de cada criadora" icon={Crown} tone="green"/><Stat id="fans-cooling" label="Esfriando" value={seg.esfriando || 0} caption="Baleias e spenders sem comprar há 10–29 dias" icon={Snowflake} tone="amber"/><Stat id="fans-new" label="Novos sem compra" value={seg.novo_sem_compra || 0} caption="Assinaram há até 3 dias e não compraram" icon={Sparkles}/><Stat id="fans-gone" label="Dormentes" value={seg.dormente || 0} caption="Compraram, mas nada há 30 dias ou mais" icon={UserMinus}/></div>
    {data && !data.fan_names_allowed && <Notice id="fans-names-notice" tone="amber">A opção "guardar nome do assinante" está desligada em Configurações: os assinantes aparecem sem nome.</Notice>}
    {tasks.length ? <section className="data-section" data-testid="fan-tasks"><div className="section-heading"><div><h2><ListChecks size={16}/> Listas de trabalho (14 dias)</h2><p>Fãs atribuídos aos chatters. "Voltou a comprar" = compra em até 3 dias depois do contato.</p></div><span className="count-label">{open} abertos · {contacted.length} contatados · {won.length} voltaram a comprar ({money(won.reduce((a, t) => a + t.converted_cents, 0))})</span></div>
      <div className="table-scroll"><table><thead><tr><th>Fã</th><th>Criadora</th><th>Chatter</th><th>Motivo</th><th>Situação</th><th>Resultado</th><th/></tr></thead><tbody>{tasks.slice(0, 50).map(t => <tr key={t.id}><td><strong>{t.fan_name || 'Sem nome'}</strong></td><td>{t.creator_name}</td><td>{t.assigned_name}</td><td>{t.reason || '—'}</td><td>{t.status === 'open' ? <Badge tone="amber">Aberto</Badge> : <Badge tone="green">Contatado {dateTime(t.contacted_at)}</Badge>}</td><td className="tabular">{t.converted_cents ? money(t.converted_cents) : '—'}</td><td><button className="icon-btn" title="Remover da lista" onClick={async () => { await api.delete(`/fan-tasks/${t.id}`); load(); }}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></section> : null}
    <div className="creator-toolbar"><div className="filter-tabs">{FILTERS.map(([k, l]) => { const n = count(k); return <button key={k} className={filter === k ? 'selected' : ''} disabled={!n && k !== 'all'} onClick={() => setFilter(k)}>{l}<span>{n}</span></button>; })}</div><div className="toolbar-right"><div className="search-field"><Search size={16}/><input placeholder="Buscar assinante..." value={search} onChange={e => setSearch(e.target.value)}/></div></div></div>
    {pickedRows.length ? <div className="assign-bar" data-testid="assign-bar"><strong>{pickedRows.length} selecionados</strong>{pickedCreators.length > 1 && <span className="inherited-label">selecione uma criadora por vez</span>}<Select id="assign-to" value={assignee} onChange={e => setAssignee(e.target.value)}><option value="">Enviar para o chatter…</option>{users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}</Select><Button onClick={assign}><Send size={14}/>Enviar para a lista</Button><Button variant="ghost" onClick={() => setPicked({})}>Limpar</Button></div> : null}
    {rows.length ? <section className="data-section"><div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Selecionar todos" checked={rows.length > 0 && rows.every(f => picked[f.creator_id + f.fan_ref])} onChange={e => setPicked(e.target.checked ? Object.fromEntries(rows.map(f => [f.creator_id + f.fan_ref, true])) : {})}/></th><th>Assinante</th><th>Criadora</th><th>Faixa</th><th>Assinatura</th><th>Gasto total</th><th>Compras</th><th>Ticket</th><th>Última compra</th><th>Ofertas</th><th>Notas</th></tr></thead><tbody>
      {rows.map(f => { const key = f.creator_id + f.fan_ref; return <tr key={key}><td><input type="checkbox" checked={!!picked[key]} onChange={e => setPicked(p => ({ ...p, [key]: e.target.checked }))}/></td>
        <td><div className="person-cell"><span className="avatar small-avatar">{initials(f.fan_name || '?')}</span><div><strong>{f.fan_name || 'Sem nome'}</strong><span>{f.first_at ? `desde ${dateTime(f.first_at).split(' ')[0]}` : 'sem compra registrada'}</span></div></div></td>
        <td>{f.creator_name}</td>
        <td><div className="tag-stack">{f.tier && <Badge tone={TIER[f.tier]?.[1]}>{TIER[f.tier]?.[0]}</Badge>}{(f.tags || []).map(t => <Badge key={t} tone={TAG[t]?.[1]}>{TAG[t]?.[0]}</Badge>)}</div></td>
        <td>{f.sub_status ? <><Badge tone={f.sub_active ? 'green' : f.sub_active === false ? 'amber' : 'neutral'}>{f.sub_status}</Badge><span className="inherited-label">{f.sub_price_cents != null ? money(f.sub_price_cents) : ''}{f.sub_duration ? ` · ${f.sub_duration}` : ''}</span></> : '—'}</td>
        <td className="tabular"><strong>{money(f.total_cents)}</strong>{f.refunded_cents ? <span className="inherited-label">estornos {money(f.refunded_cents)}</span> : null}</td><td>{f.purchases}</td><td className="tabular">{money(f.ticket_cents)}</td>
        <td>{f.last_at ? <>{dateTime(f.last_at)}<span className="inherited-label">{f.days_since_last === 0 ? 'hoje' : `há ${f.days_since_last} dias`} · {PROD[f.last_product] || ''}</span></> : '—'}</td>
        <td>{f.offers_sent ? `${f.offers_paid}/${f.offers_sent}` : '—'}</td>
        <td><button className="icon-btn" title="Anotações e cartão do fã" onClick={() => openNotes(f)}><StickyNote size={15}/>{f.notes_count ? <span className="note-count">{f.notes_count}</span> : null}</button></td></tr>; })}
    </tbody></table></div></section> : <Empty id="fans-empty" icon={Users} title="Nenhum assinante no filtro" description="As compras entram pelo extrato lido no app desktop; a situação da assinatura, pela lista de assinantes do Meu Privacy."/>}
    <Notice id="fans-notice">Faixas por criadora: Baleia = top 5% do gasto no período; Spender = os 15% seguintes. Esfriando = baleia ou spender sem comprar há 10–29 dias; Dormente = 30 dias ou mais. Só nome de exibição, valores, datas e as anotações da equipe; nada de mensagem.</Notice>
    <Modal wide open={!!notesFor} onClose={() => setNotesFor(null)} title={notesFor ? `${notesFor.fan_name || 'Fã'} · ${notesFor.creator_name}` : ''} description="O mesmo cartão que o chatter vê no app ao abrir a conversa." id="fan-card-modal">
      {card ? <div className="fan-card-panel"><div className="fan-card-kpis"><div><span>Gasto total</span><strong>{money(card.total_cents)}</strong></div><div><span>Ticket médio</span><strong>{money(card.ticket_cents)}</strong></div><div><span>Última compra</span><strong>{card.days_since_last == null ? '—' : card.days_since_last === 0 ? 'hoje' : `há ${card.days_since_last} dias`}</strong></div></div>
        {card.suggestion && <Notice id="fan-card-tip">{card.suggestion}</Notice>}
        <h3>Anotações da equipe</h3>{card.notes.length ? card.notes.map(n => <div key={n.id} className="fan-note"><p>{n.text}</p><small>{n.author_name} · {dateTime(n.created_at)}</small><button className="icon-btn" title="Apagar" onClick={() => delNote(n.id)}><Trash2 size={13}/></button></div>) : <p className="body-muted">Nenhuma anotação ainda.</p>}
        <form onSubmit={addNote} className="fan-note-form"><input value={noteText} maxLength={300} onChange={e => setNoteText(e.target.value)} placeholder="Ex.: gosta de conteúdo exclusivo; aniversário 12/10"/><Button type="submit">Salvar</Button></form>
        <p className="body-muted">Evite dados pessoais sensíveis (telefone, endereço, saúde) nas anotações.</p></div> : <p className="body-muted">Carregando…</p>}
    </Modal></>;
}
