import React from 'react';
import { Timer, Hourglass, MessageSquare, AlarmClock, Download, Clock3 } from 'lucide-react';
import { toast } from 'sonner';
import { useApp } from '../App';
import { duration, dateTime, download, errorText } from '../lib/api';
import { PageHeading, Stat, Button, Empty, Notice, Badge, Avatar } from '../components/Common';
import { useMetrics, MetricFilters } from '../components/MetricFilters';
export default function Operation() {
  const metrics = useMetrics(), s = metrics.data?.summary || {}, { config } = useApp();
  const pics = s.operator_avatars || {}; const Who = ({ id, name }) => <span className="person-cell"><Avatar name={name} src={pics[id] || null} size={26}/><span>{name}</span></span>;
  return <><PageHeading eyebrow="ACOMPANHAMENTO DO ATENDIMENTO" title="Operação" description="O tempo conta. O contexto também."><Button variant="outline" data-testid="export-operation" onClick={() => download(`/reports/export?kind=summary&${metrics.query}`, 'vertice-operacao.csv').catch(e => toast.error(errorText(e)))}><Download size={16}/>Exportar</Button></PageHeading><MetricFilters metrics={metrics}/>
    <div className="stats-grid"><Stat id="mean-response" icon={Timer} label="Tempo médio de resposta" value={duration(s.mean_seconds)} caption={`${s.response_count || 0} respostas com sequência suficiente`}/><Stat id="median-response" icon={Clock3} label="Mediana de resposta" value={duration(s.median_seconds)} caption="Somente intervalos verificáveis"/><Stat id="pending-conversations" icon={Hourglass} label="Pendências observadas" value={s.pending_count ?? '—'} caption="A espera não reinicia a cada turno"/><Stat id="late-conversations" tone="amber" icon={AlarmClock} label="Acima da meta" value={s.late_count ?? '—'} caption={`Meta de resposta: ${config.sla_minutes} minutos`}/></div>
    {(() => { const ops = Object.entries(s.response_by_operator || {}).sort((a, b) => (a[1].mean_seconds ?? 1e12) - (b[1].mean_seconds ?? 1e12)); return <section className="data-section"><div className="section-heading"><div><h2 data-testid="by-operator-title">Tempo de resposta por chatter</h2><p>Do primeiro recado do fã sem resposta até a resposta, pelo chatter do turno. Meta: {config.sla_minutes} min.</p></div><span className="count-label">{ops.length}</span></div>{ops.length ? <div className="table-scroll"><table><thead><tr><th>Chatter</th><th>Respostas</th><th>Média</th><th>Mediana</th><th>Mais lenta</th><th>Acima da meta</th><th>Esperando agora</th></tr></thead><tbody>{ops.map(([name, o]) => <tr key={name} data-testid={`by-operator-${o.operator_id || 'none'}`}><td><strong><Who id={o.operator_id} name={name}/></strong></td><td className="tabular">{o.count}</td><td className="tabular">{duration(o.mean_seconds)}</td><td className="tabular">{duration(o.median_seconds)}</td><td className="tabular">{duration(o.max_seconds)}</td><td>{o.count ? <Badge tone={o.late / o.count > 0.2 ? 'red' : 'green'}>{o.late} de {o.count} ({Math.round(o.late / o.count * 100)}%)</Badge> : '—'}</td><td className="tabular">{o.pending || 0}</td></tr>)}</tbody></table></div> : <div className="inline-empty">Os tempos por chatter aparecem quando houver respostas observadas no período.</div>}</section>; })()}
    <section className="data-section"><div className="section-heading"><div><h2 data-testid="pending-title">Fila de pendências</h2><p data-testid="pending-description">Da espera mais longa para a mais recente.</p></div><span className="count-label" data-testid="pending-count">{metrics.data?.pending.length || 0}</span></div>{metrics.data?.pending.length ? <div className="table-scroll"><table><thead><tr><th>Criadora</th><th>Assinante</th><th>Operador do início</th><th>Início da espera</th><th>Tempo de espera</th><th>Situação</th></tr></thead><tbody>{metrics.data.pending.map(p => <tr data-testid={`pending-row-${p.id}`} key={p.id}><td><strong>{p.creator_name}</strong></td><td>{p.fan_name || '—'}</td><td><Who id={p.operator_id} name={p.operator_name}/></td><td>{dateTime(p.started_at)}</td><td className="tabular">{duration(p.seconds)}</td><td><Badge tone={p.late ? 'red' : 'green'} testId={`pending-state-${p.id}`}>{p.late ? 'Acima da meta' : 'Dentro da meta'}</Badge>{p.inherited && <span className="inherited-label" data-testid={`pending-inherited-${p.id}`}>Herdada de outro turno</span>}</td></tr>)}</tbody></table></div> : <Empty id="pending-empty" icon={MessageSquare} title="Nenhuma pendência observada" description="Sem uma amostra suficiente, ausência de registros não significa ausência de espera."/>}</section>
    <section className="data-section"><div className="section-heading"><h2 data-testid="responses-title">Respostas observadas</h2><span className="subtle-label" data-testid="response-sample">{s.sample_count || 0} intervalos na amostra · {s.incomplete_count || 0} incompletos excluídos</span></div>{metrics.data?.responses.length ? <div className="table-scroll"><table><thead><tr><th>Criadora</th><th>Assinante</th><th>Operador da resposta</th><th>Resposta em</th><th>Tempo total</th><th>Troca de turno</th></tr></thead><tbody>{metrics.data.responses.map(r => <tr data-testid={`response-row-${r.id}`} key={r.id}><td>{r.creator_name}</td><td>{r.fan_name || '—'}</td><td><Who id={r.operator_id} name={r.operator_name}/></td><td>{dateTime(r.responded_at)}</td><td>{duration(r.seconds)}</td><td>{r.inherited ? 'Pendência herdada' : 'Não identificada'}</td></tr>)}</tbody></table></div> : <div className="inline-empty" data-testid="responses-empty">Os intervalos com início e resposta verificáveis aparecerão aqui.</div>}</section><Notice id="operation-limits">Amostra restrita às telas observadas. Mensagens consecutivas não reiniciam a espera; sequências incompletas não entram na média como zero.</Notice></>;
}