import React, { useState, useEffect, useCallback } from 'react';
import { ClipboardCheck, Plus, Check, AlertCircle, Minus, ArrowRight, Square } from 'lucide-react';
import { toast } from 'sonner';
import { useApp } from '../App';
import { api, errorText, dateTime } from '../lib/api';
import { PageHeading, Button, Badge, Modal, Field, Select, Submit, FormError, Empty, Notice } from '../components/Common';
import { QualityBoard } from '../components/QualityBoard';
import { QualityAI } from '../components/QualityAI';
import { FilterBar, usePersistedFilters } from '../components/MetricFilters';
export const criteria = [['resposta', 'Resposta à pergunta', 'A dúvida apresentada recebeu uma resposta adequada?'], ['continuidade', 'Continuidade da conversa', 'O atendimento manteve o contexto visível?'], ['clareza', 'Clareza', 'A comunicação foi clara e compreensível?'], ['orientacoes', 'Orientações da criadora', 'As orientações aplicáveis foram respeitadas?'], ['acompanhamento', 'Dúvidas e compromissos', 'Houve acompanhamento dos pontos em aberto?']];
const labels = { adequado: 'Adequado', atencao: 'Precisa de atenção', nao_avaliavel: 'Não avaliável' };
export default function Quality() {
  const { creators, user, config, refresh } = useApp(); const [reviews, setReviews] = useState([]), [modal, setModal] = useState(false), [creatorId, setCreatorId] = useState(''), [ack, setAck] = useState(false), [error, setError] = useState(''), [busy, setBusy] = useState(false), [detail, setDetail] = useState(null);
  const [answers, setAnswers] = useState(Object.fromEntries(criteria.map(([k]) => [k, 'nao_avaliavel'])));
  const [filters, setFilters] = usePersistedFilters(), [reloadKey, setReloadKey] = useState(0);
  const load = useCallback(() => api.get('/reviews').then(r => setReviews(r.data)).catch(e => toast.error(errorText(e))), []);
  useEffect(() => { load(); }, [load]);
  const current = creators.find(c => c.id === creatorId), session = current?.review;
  async function begin(e) { e.preventDefault(); setBusy(true); setError(''); try { await api.post(`/creators/${creatorId}/review/start`, { acknowledge_read: ack }); await refresh(); toast.success('Revisão local iniciada. O turno permanece pausado.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function save(e) { e.preventDefault(); setBusy(true); setError(''); try { await api.post('/reviews', { creator_id: creatorId, review_session_id: session.id, answers }); await api.post(`/creators/${creatorId}/review/end`); await refresh(); await load(); setModal(false); toast.success('Avaliação registrada. Retome o turno quando o atendimento estiver pronto.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function end(c) { try { await api.post(`/creators/${c.id}/review/end`); await refresh(); setModal(false); toast.success('Revisão encerrada; o turno continua pausado.'); } catch (e) { toast.error(errorText(e)); } }
  const open = id => { setCreatorId(id || ''); setAck(false); setError(''); setAnswers(Object.fromEntries(criteria.map(([k]) => [k, 'nao_avaliavel']))); setModal(true); };
  return <><PageHeading eyebrow="SUPERVISÃO COM CONTEXTO" title="Qualidade" description="Boletim de cada chatter, alertas de agora e análises da equipe."><Button data-testid="new-review" onClick={() => open('')}><Plus size={16}/>Revisão manual</Button></PageHeading><FilterBar filters={filters} setFilters={setFilters} onReload={() => { setReloadKey(k => k + 1); load(); }}/><QualityBoard filters={filters} reloadKey={reloadKey}/><QualityAI filters={filters} reloadKey={reloadKey}/>
    {creators.filter(c => c.review).map(c => <div className="active-review" key={c.id} data-testid={`active-review-${c.id}`}><Badge tone="amber" testId={`review-badge-${c.id}`}>Revisão aberta</Badge><strong>{c.name}</strong><span className="body-muted">Turno de {c.review.operator_name}</span><div className="row-actions">{c.review.manager_id === user.id && <Button variant="outline" data-testid={`continue-review-${c.id}`} onClick={() => open(c.id)}>Continuar<ArrowRight size={14}/></Button>}<Button variant="ghost" data-testid={`end-review-${c.id}`} onClick={() => end(c)}><Square size={14}/>Encerrar revisão</Button></div></div>)}
    <section className="data-section"><div className="section-heading"><div><h2 data-testid="quality-history-title">Avaliações do supervisor</h2><p data-testid="quality-history-description">Somente critérios estruturados, sem conteúdo das conversas.</p></div><span className="count-label" data-testid="review-count">{reviews.length}</span></div>{reviews.length ? <div className="table-scroll"><table><thead><tr><th>Criadora</th><th>Operador</th><th>Supervisor</th><th>Revisão em</th><th>Critérios avaliáveis</th><th/></tr></thead><tbody>{reviews.map(r => <tr key={r.id} data-testid={`review-row-${r.id}`}><td><strong>{r.creator_name}</strong></td><td>{r.operator_name}</td><td>{r.manager_name}</td><td>{dateTime(r.created_at)}</td><td>{Object.values(r.answers).filter(a => a !== 'nao_avaliavel').length} de 5</td><td><button data-testid={`view-review-${r.id}`} className="icon-btn" title="Ver avaliação" onClick={() => setDetail(r)}><ArrowRight size={17}/></button></td></tr>)}</tbody></table></div> : <Empty id="quality-empty" icon={ClipboardCheck} title="Boas avaliações começam pelo contexto." description="As revisões locais registradas pelo supervisor vão compor este histórico."/>}</section><Notice id="quality-privacy">Antes de revisar, pause o atendimento do perfil. Abrir conversas na Privacy pode marcá-las como lidas. O sistema não enviará mensagens.</Notice>
    <Modal title={session ? `Avaliação · ${current.name}` : 'Iniciar revisão local'} description={session ? `Turno de ${session.operator_name} · ${dateTime(session.period_start)}` : 'A consulta acontece na janela local da criadora, sob seu controle.'} open={modal} onClose={() => setModal(false)} id="quality-form-modal">{!session ? <form className="form-stack" onSubmit={begin}><Field id="review-creator" label="Criadora"><Select id="review-creator" value={creatorId} onChange={e => setCreatorId(e.target.value)} required><option value="">Selecione uma criadora</option>{creators.map(c => <option key={c.id} value={c.id}>{c.name}{c.shift?.paused ? ' · Turno pausado' : ''}</option>)}</Select></Field><Notice id="review-browser-warning" tone="amber">O navegador deve estar aberto na estação conectada e o turno pausado. Não há navegação automática ou reprodução remota.</Notice><label className="checkbox-label"><input type="checkbox" data-testid="review-read-acknowledge" checked={ack} onChange={e => setAck(e.target.checked)} required/><span>Estou no computador da agência e reconheço que abrir conversas pode marcá-las como lidas.</span></label><FormError error={error}/><Submit id="start-local-review" busy={busy}>Assumir revisão local<ArrowRight size={15}/></Submit></form> : <form className="form-stack" onSubmit={save}><div className="criteria-list">{criteria.map(([key, label, description]) => <div className="criterion" key={key}><strong data-testid={`criterion-${key}`}>{label}</strong><p>{description}</p><div className="criterion-options">{[['adequado', Check], ['atencao', AlertCircle], ['nao_avaliavel', Minus]].map(([value, Icon]) => <button type="button" key={value} data-testid={`criterion-${key}-${value}`} className={answers[key] === value ? `selected ${value}` : ''} aria-pressed={answers[key] === value} onClick={() => setAnswers(a => ({ ...a, [key]: value }))} title={labels[value]}><Icon size={13}/>{labels[value]}</button>)}</div></div>)}</div>{!config.storage_allowed && <Notice tone="amber" id="review-storage-disabled">O histórico está desabilitado. Confirme a permissão para guardar métricas e avaliações nas configurações.</Notice>}<FormError error={error}/><div className="form-actions"><Button type="button" variant="outline" data-testid="cancel-local-review" onClick={() => end(current)}>Encerrar sem salvar</Button><Submit busy={busy} id="save-quality-review">Salvar e finalizar</Submit></div></form>}</Modal>
    <Modal title={`Avaliação · ${detail?.creator_name}`} description={`${detail?.operator_name || ''} · ${dateTime(detail?.created_at)}`} open={!!detail} onClose={() => setDetail(null)} id="review-detail-modal"><div className="review-details">{criteria.map(([key, label]) => <div key={key} data-testid={`review-detail-${key}`}><span>{label}</span><Badge tone={detail?.answers[key] === 'adequado' ? 'green' : detail?.answers[key] === 'atencao' ? 'amber' : 'neutral'} testId={`review-detail-answer-${key}`}>{labels[detail?.answers[key]]}</Badge></div>)}</div><p className="body-muted" data-testid="review-detail-period">Período do turno: {dateTime(detail?.period_start)} a {dateTime(detail?.period_end)}</p></Modal>
  </>;
}