import React, { useState, useEffect } from 'react';
import { Download, FileChartColumn, Receipt, ClipboardCheck, History, ChevronRight } from 'lucide-react';
import { toast } from 'sonner';
import { api, errorText, download, dateTime } from '../lib/api';
import { PageHeading, Button, Empty, Modal, Notice } from '../components/Common';
import { MetricFilters, useMetrics } from '../components/MetricFilters';
const types = [['summary', 'Operação', 'Tempos, pendências e tamanho da amostra.', FileChartColumn], ['sales', 'Vendas', 'Valores e associações ao turno registrado.', Receipt], ['reviews', 'Qualidade', 'Critérios estruturados de cada revisão.', ClipboardCheck], ['audit', 'Histórico de ajustes', 'Responsáveis, motivos e alterações.', History]];
export default function Reports() {
  const metrics = useMetrics(); const [audit, setAudit] = useState([]), [detail, setDetail] = useState(null);
  useEffect(() => { api.get('/audit').then(r => setAudit(r.data)).catch(e => toast.error(errorText(e))); }, []);
  return <><PageHeading eyebrow="HISTÓRICO E TRANSPARÊNCIA" title="Relatórios" description="Uma leitura do período, com a origem e os limites de cada resultado."/><MetricFilters metrics={metrics}/><div className="report-grid">{types.map(([kind, title, description, Icon]) => <article className="report-card" key={kind}><Icon size={23} strokeWidth={1.5}/><h3 data-testid={`report-title-${kind}`}>{title}</h3><p data-testid={`report-description-${kind}`}>{description}</p><Button data-testid={`download-report-${kind}`} variant="outline" onClick={() => download(`/reports/export?kind=${kind}&${metrics.query}`, `vertice-${kind}.csv`).catch(e => toast.error(errorText(e)))}><Download size={15}/>Exportar CSV</Button></article>)}</div><Notice id="report-coverage-notice">Os relatórios respeitam o período retido e a amostra observada. Ajustes mostram todas as criadoras no período. Não há conteúdo das conversas ou identificação de assinantes.</Notice>
    <section className="data-section"><div className="section-heading"><div><h2 data-testid="audit-title">Histórico de ações e ajustes</h2><p data-testid="audit-description">Histórico geral do workspace · os filtros acima se aplicam aos arquivos exportados.</p></div></div>{audit.length ? <div className="table-scroll"><table><thead><tr><th>Ação</th><th>Registro</th><th>Responsável</th><th>Data · Brasília</th><th/></tr></thead><tbody>{audit.map(a => <tr key={a.id} data-testid={`audit-row-${a.id}`}><td><strong>{a.action}</strong></td><td>{a.target}</td><td>{a.actor}</td><td>{dateTime(a.created_at)}</td><td><button title="Detalhes do registro" className="icon-btn" data-testid={`audit-detail-${a.id}`} onClick={() => setDetail(a)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table></div> : <Empty id="audit-empty" icon={History} title="Histórico preservado, gestão transparente" description="Cadastros, mudanças de turno e ajustes serão registrados aqui."/>}</section><Modal title="Detalhes do registro" open={!!detail} onClose={() => setDetail(null)} id="audit-detail-modal"><div className="audit-detail"><strong data-testid="audit-detail-action">{detail?.action}</strong><p data-testid="audit-detail-actor">{detail?.actor} · {dateTime(detail?.created_at)}</p><p data-testid="audit-detail-reason">Motivo: {detail?.reason || 'Não se aplica a esta ação.'}</p>{detail?.changes && <pre data-testid="audit-detail-changes">{JSON.stringify(detail.changes, null, 2)}</pre>}</div></Modal></>;
}