import React, { useState } from 'react';
import { ShoppingBag, Banknote, Undo2, UserRoundSearch, Download, Receipt, Pencil } from 'lucide-react';
import { toast } from 'sonner';
import { api, money, dateTime, download, errorText } from '../lib/api';
import { PageHeading, Stat, Button, Empty, Notice, Badge, Modal, Field, Select, FormError, Submit } from '../components/Common';
import { useMetrics, MetricFilters } from '../components/MetricFilters';
const origins = { chat: 'Venda de chat', subscription: 'Assinatura', renewal: 'Renovação', tip: 'Mimo', unknown: 'Não identificada' };
const statuses = { confirmed: 'Confirmada', refunded: 'Estornada', cancelled: 'Cancelada', unknown: 'Não identificada' };
export default function Sales() {
  const metrics = useMetrics(), s = metrics.data?.summary || {};
  const [editing, setEditing] = useState(null), [shifts, setShifts] = useState([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function edit(sale) { try { const r = await api.get('/shifts'); setShifts(r.data.filter(s => s.creator_id === sale.creator_id)); setEditing(sale); setError(''); } catch (e) { toast.error(errorText(e)); } }
  async function save(e) { e.preventDefault(); setBusy(true); const form = Object.fromEntries(new FormData(e.currentTarget)); try { await api.patch(`/sales/${editing.id}/assignment`, { ...form, shift_id: form.shift_id || null }); setEditing(null); await metrics.reload(); toast.success('Associação corrigida com histórico.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  return <><PageHeading eyebrow="RESULTADOS COMERCIAIS" title="Vendas" description="Resultados associados ao turno. Sem atribuições por suposição."><Button data-testid="export-sales" variant="outline" onClick={() => download(`/reports/export?kind=sales&${metrics.query}`, 'vertice-vendas.csv').catch(e => toast.error(errorText(e)))}><Download size={16}/>Exportar vendas</Button></PageHeading><MetricFilters metrics={metrics}/><div className="stats-grid"><Stat id="sales-value" label="Vendas de chat confirmadas" value={money(s.confirmed_cents)} caption="Valor bruto observado, sem estornos" icon={Banknote} tone="green"/><Stat id="sales-count" label="Vendas confirmadas" value={s.confirmed_count ?? '—'} caption="Origem e confirmação identificadas" icon={ShoppingBag}/><Stat id="sales-refunds" label="Estornos observados" value={money(s.refunded_cents)} caption={`Cancelamentos: ${money(s.cancelled_cents)}`} icon={Undo2}/><Stat id="sales-unassigned" label="Sem atribuição" value={s.sales_sample ? s.unassigned_sales : '—'} caption="Origem, horário ou turno insuficientes" icon={UserRoundSearch}/></div>
    <section className="data-section"><div className="section-heading"><div><h2 data-testid="sales-table-title">Vendas associadas ao turno</h2><p data-testid="sales-table-caption">Associação pelo horário de confirmação, não de leitura.</p></div><span className="count-label" data-testid="sales-sample-count">{s.sales_sample || 0} registros</span></div>{metrics.data?.sales.length ? <div className="table-scroll"><table><thead><tr><th>Criadora</th><th>Assinante</th><th>Operador associado</th><th>Confirmação</th><th>Origem</th><th>Valor bruto</th><th>Situação</th><th/></tr></thead><tbody>{metrics.data.sales.map(sale => <tr key={sale.id} data-testid={`sale-row-${sale.id}`}><td><strong>{sale.creator_name}</strong></td><td>{sale.fan_name || (sale.fan_ref ? 'Não guardado' : '—')}</td><td>{sale.operator_name}{sale.assignment_type === 'manual' && <span className="inherited-label" data-testid={`sale-manual-${sale.id}`}>Ajuste manual auditado</span>}</td><td>{dateTime(sale.confirmed_at)}</td><td>{origins[sale.sale_origin]}</td><td className="tabular">{money(sale.amount_cents)}</td><td><Badge testId={`sale-status-${sale.id}`} tone={sale.sale_status === 'confirmed' ? 'green' : 'amber'}>{statuses[sale.sale_status]}</Badge></td><td><button title="Corrigir associação" className="icon-btn" data-testid={`edit-sale-assignment-${sale.id}`} onClick={() => edit(sale)}><Pencil size={15}/></button></td></tr>)}</tbody></table></div> : <Empty id="sales-empty" icon={Receipt} title="Resultados que precisam de evidência, não estimativas." description="Vendas com valor, origem e confirmação visíveis aparecerão aqui após a validação local."/>}</section><Notice id="sales-disclaimer">A associação ao turno não comprova autoria ou causalidade da compra. Não calcula comissões nem substitui o financeiro oficial da Privacy.</Notice>
    <Modal title="Corrigir associação da venda" description="A mudança será identificada como ajuste manual e não altera o financeiro da Privacy." open={!!editing} onClose={() => setEditing(null)} id="sale-assignment-modal"><form className="form-stack" onSubmit={save}><Field id="sale-assignment-shift" label="Turno associado"><Select id="sale-assignment-shift" name="shift_id" defaultValue={editing?.shift_id || ''}><option value="" label="Manter sem atribuição"/>{shifts.map(s => <option value={s.id} key={s.id} label={`${s.operator_name} · ${dateTime(s.started_at)}`}/>)}</Select></Field><Field id="sale-assignment-reason" name="reason" label="Motivo da correção" minLength={5} maxLength={200} required placeholder="Sem conteúdo de conversas ou dados de assinantes"/><FormError error={error}/><Submit busy={busy} id="save-sale-assignment">Salvar ajuste</Submit></form></Modal></>;
}