import React, { useState } from 'react';
import { ShoppingBag, Banknote, Undo2, UserRoundSearch, Download, Receipt, Pencil } from 'lucide-react';
import { toast } from 'sonner';
import { api, money, dateTime, download, errorText } from '../lib/api';
import { PageHeading, Stat, Button, Empty, Notice, Badge, Modal, Field, Select, FormError, Submit } from '../components/Common';
import { useMetrics, MetricFilters } from '../components/MetricFilters';
const origins = { chat: 'Venda de chat', subscription: 'Assinatura', renewal: 'Renovação', post: 'Publicação paga', tip: 'Mimo', unknown: 'Não identificada' };
const statuses = { confirmed: 'Confirmada', pending: 'A receber', refunded: 'Estornada', cancelled: 'Cancelada', unknown: 'Não identificada' };
const tones = { confirmed: 'green', pending: 'amber', refunded: 'red', cancelled: 'red', unknown: 'amber' };
function Breakdown({ id, title, caption, rows, labels }) {
  const entries = Object.entries(rows || {}).sort((a, b) => b[1].cents - a[1].cents);
  return <section className="data-section" data-testid={id}><div className="section-heading"><div><h2>{title}</h2><p>{caption}</p></div></div>{entries.length ? <div className="table-scroll"><table><thead><tr><th>{labels.key}</th><th>Registros</th><th>Valor bruto</th><th>Comissão da criadora</th><th>A receber</th></tr></thead><tbody>{entries.map(([k, v]) => <tr key={k} data-testid={`${id}-${k}`}><td><strong>{labels.map ? (labels.map[k] || k) : k}</strong></td><td>{v.count}</td><td className="tabular">{money(v.cents)}</td><td className="tabular">{v.commission_cents ? money(v.commission_cents) : '—'}</td><td className="tabular">{v.pending_cents ? money(v.pending_cents) : '—'}</td></tr>)}</tbody></table></div> : <div className="inline-empty">Sem registros no período.</div>}</section>;
}
export default function Sales() {
  const metrics = useMetrics(), s = metrics.data?.summary || {};
  const [q, setQ] = useState(''), [origin, setOrigin] = useState(''), [status, setStatus] = useState('');
  const salesRows = (metrics.data?.sales || []).filter(x => (!origin || x.sale_origin === origin) && (!status || x.sale_status === status) && (!q || (x.fan_name || '').toLowerCase().includes(q.toLowerCase()))).sort((a, b) => (b.confirmed_at || '').localeCompare(a.confirmed_at || ''));
  const [editing, setEditing] = useState(null), [shifts, setShifts] = useState([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  async function edit(sale) { try { const r = await api.get('/shifts'); setShifts(r.data.filter(s => s.creator_id === sale.creator_id)); setEditing(sale); setError(''); } catch (e) { toast.error(errorText(e)); } }
  async function save(e) { e.preventDefault(); setBusy(true); const form = Object.fromEntries(new FormData(e.currentTarget)); try { await api.patch(`/sales/${editing.id}/assignment`, { ...form, shift_id: form.shift_id || null }); setEditing(null); await metrics.reload(); toast.success('Associação corrigida com histórico.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  return <><PageHeading eyebrow="RESULTADOS COMERCIAIS" title="Vendas" description="Resultados associados ao turno. Sem atribuições por suposição."><Button data-testid="export-sales" variant="outline" onClick={() => download(`/reports/export?kind=sales&${metrics.query}`, 'vertice-vendas.csv').catch(e => toast.error(errorText(e)))}><Download size={16}/>Exportar vendas</Button></PageHeading><MetricFilters metrics={metrics}/><div className="stats-grid"><Stat id="sales-value" label="Vendas de chat confirmadas" value={money(s.confirmed_cents)} caption="Valor bruto observado, sem estornos" icon={Banknote} tone="green"/><Stat id="sales-count" label="Vendas confirmadas" value={s.confirmed_count ?? '—'} caption="Origem e confirmação identificadas" icon={ShoppingBag}/><Stat id="sales-refunds" label="Estornos observados" value={money(s.refunded_cents)} caption={`Cancelamentos: ${money(s.cancelled_cents)}`} icon={Undo2}/><Stat id="sales-unassigned" label="Sem atribuição" value={s.sales_sample ? s.unassigned_sales : '—'} caption="Origem, horário ou turno insuficientes" icon={UserRoundSearch}/></div>
    <div className="stats-grid"><Stat id="sales-gross" label="Faturamento bruto da criadora" value={money(s.gross_cents)} caption="Todas as origens lidas do extrato, sem estornos" icon={Receipt}/><Stat id="sales-commission" label="Comissão da criadora" value={money(s.commission_cents)} caption="Valor líquido informado pela Privacy" icon={Banknote} tone="green"/><Stat id="sales-pending" label="A receber" value={money(s.pending_cents)} caption="Vendas de chat ainda em processamento" icon={ShoppingBag}/><Stat id="sales-extrato" label="Vendas do extrato" value={s.sales_sample ? `${s.extrato_count || 0} de ${s.sales_sample}` : '—'} caption="Registros com hora, produto e pagamento exatos" icon={UserRoundSearch}/></div>
    <div className="two-col"><Breakdown id="sales-by-origin" title="Por produto" caption="Compare com Meu Privacy → Faturamento no mesmo período." rows={s.by_origin} labels={{ key: 'Produto', map: origins }}/><Breakdown id="sales-by-payment" title="Por forma de pagamento" caption="Como lido no extrato da Privacy." rows={s.by_payment} labels={{ key: 'Pagamento' }}/></div>
    <section className="data-section" data-testid="offers-by-operator"><div className="section-heading"><div><h2>Funil de ofertas por chatter</h2><p>Ofertas de mídia paga enviadas no chat (etiqueta "ainda não pago" / "pago") e quantas o fã pagou. Lidas na conversa aberta.</p></div><span className="count-label">{s.offers_sent || 0} enviadas · {s.offers_paid || 0} pagas</span></div>{Object.keys(s.offers_by_operator || {}).length ? <div className="table-scroll"><table><thead><tr><th>Chatter</th><th>Enviadas</th><th>Pagas</th><th>Conversão</th><th>Valor ofertado</th><th>Valor pago</th><th>Oferta média</th></tr></thead><tbody>{Object.entries(s.offers_by_operator).sort((a, b) => b[1].paid_cents - a[1].paid_cents).map(([name, v]) => <tr key={name}><td><strong>{name}</strong></td><td>{v.sent}</td><td>{v.paid}</td><td><Badge tone={v.conversion == null ? 'neutral' : v.conversion >= 30 ? 'green' : 'amber'}>{v.conversion == null ? '—' : `${v.conversion}%`}</Badge></td><td className="tabular">{money(v.sent_cents)}</td><td className="tabular">{money(v.paid_cents)}</td><td className="tabular">{money(v.sent ? Math.round(v.sent_cents / v.sent) : null)}</td></tr>)}</tbody></table></div> : <div className="inline-empty">Sem ofertas observadas no período. Elas entram quando o chatter está com a conversa aberta no app.</div>}</section>
    <section className="data-section" data-testid="sales-by-operator"><div className="section-heading"><div><h2>Vendas de chat por chatter</h2><p>Só vendas de chat com horário conhecido, associadas pelo turno. Sem estornos.</p></div></div>{Object.keys(s.by_operator || {}).length ? <div className="table-scroll"><table><thead><tr><th>Chatter</th><th>Vendas</th><th>Valor bruto</th><th>Ticket médio</th></tr></thead><tbody>{Object.entries(s.by_operator).sort((a, b) => b[1].cents - a[1].cents).map(([name, v]) => <tr key={name}><td><strong>{name}</strong></td><td>{v.count}</td><td className="tabular">{money(v.cents)}</td><td className="tabular">{money(Math.round(v.cents / v.count))}</td></tr>)}</tbody></table></div> : <div className="inline-empty">Sem vendas de chat no período.</div>}</section>
    <section className="data-section"><div className="section-heading"><div><h2 data-testid="sales-table-title">Vendas associadas ao turno</h2><p data-testid="sales-table-caption">Associação pelo horário de confirmação, não de leitura.</p></div><span className="count-label" data-testid="sales-sample-count">{salesRows.length === (s.sales_sample || 0) ? `${s.sales_sample || 0} registros` : `${salesRows.length} de ${s.sales_sample || 0}`}</span></div>{metrics.data?.sales.length ? <div className="sales-table-filters"><input className="table-search" placeholder="Buscar assinante..." value={q} onChange={e => setQ(e.target.value)}/><Select id="sales-origin-filter" value={origin} onChange={e => setOrigin(e.target.value)}><option value="">Todos os produtos</option>{Object.entries(origins).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select><Select id="sales-status-filter" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todas as situações</option>{Object.entries(statuses).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</Select><span className="body-muted">Criadora, chatter e período: filtros do topo da página.</span></div> : null}{salesRows.length ? <div className="table-scroll"><table><thead><tr><th>Criadora</th><th>Assinante</th><th>Operador associado</th><th>Confirmação</th><th>Origem</th><th>Pagamento</th><th>Valor bruto</th><th>Comissão</th><th>Situação</th><th/></tr></thead><tbody>{salesRows.map(sale => <tr key={sale.id} data-testid={`sale-row-${sale.id}`}><td><strong>{sale.creator_name}</strong></td><td>{sale.fan_name || (sale.fan_ref ? 'Não guardado' : '—')}</td><td>{sale.operator_name}{sale.assignment_type === 'manual' && <span className="inherited-label" data-testid={`sale-manual-${sale.id}`}>Ajuste manual auditado</span>}</td><td>{dateTime(sale.confirmed_at)}</td><td>{origins[sale.sale_origin]}{sale.sale_source === 'extrato' && <span className="inherited-label">Extrato</span>}</td><td>{sale.payment_method || '—'}</td><td className="tabular">{money(sale.amount_cents)}</td><td className="tabular">{sale.commission_cents != null ? money(sale.commission_cents) : '—'}</td><td><Badge testId={`sale-status-${sale.id}`} tone={tones[sale.sale_status] || 'amber'}>{statuses[sale.sale_status]}</Badge></td><td><button title="Corrigir associação" className="icon-btn" data-testid={`edit-sale-assignment-${sale.id}`} onClick={() => edit(sale)}><Pencil size={15}/></button></td></tr>)}</tbody></table></div> : <Empty id="sales-empty" icon={Receipt} title="Resultados que precisam de evidência, não estimativas." description="Vendas com valor, origem e confirmação visíveis aparecerão aqui após a validação local."/>}</section><Notice id="sales-disclaimer">A associação ao turno não comprova autoria ou causalidade da compra. A comissão exibida é a informada no extrato da Privacy; o financeiro oficial continua sendo o da Privacy.</Notice>
    <Modal title="Corrigir associação da venda" description="A mudança será identificada como ajuste manual e não altera o financeiro da Privacy." open={!!editing} onClose={() => setEditing(null)} id="sale-assignment-modal"><form className="form-stack" onSubmit={save}><Field id="sale-assignment-shift" label="Turno associado"><Select id="sale-assignment-shift" name="shift_id" defaultValue={editing?.shift_id || ''}><option value="" label="Manter sem atribuição"/>{shifts.map(s => <option value={s.id} key={s.id} label={`${s.operator_name} · ${dateTime(s.started_at)}`}/>)}</Select></Field><Field id="sale-assignment-reason" name="reason" label="Motivo da correção" minLength={5} maxLength={200} required placeholder="Sem conteúdo de conversas ou dados de assinantes"/><FormError error={error}/><Submit busy={busy} id="save-sale-assignment">Salvar ajuste</Submit></form></Modal></>;
}