import React, { useState } from 'react';
import { ShieldCheck, Trash2, Puzzle, Download, ArrowRight } from 'lucide-react';
import { toast } from 'sonner';
import { Link } from 'react-router-dom';
import { useApp } from '../App';
import { api, errorText, download } from '../lib/api';
import { PageHeading, Button, Field, Select, Submit, FormError, Notice, Modal } from '../components/Common';
export default function Settings() {
  const { config, setConfig, creators } = useApp();
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [allowed, setAllowed] = useState(config.storage_allowed), [fanNames, setFanNames] = useState(!!config.fan_names_allowed), [confirm, setConfirm] = useState(null), [reason, setReason] = useState(''), [scope, setScope] = useState('');
  async function save(e) { e.preventDefault(); const form = Object.fromEntries(new FormData(e.currentTarget)); const body = { ...form, sla_minutes: Number(form.sla_minutes), retention_days: Number(form.retention_days), storage_allowed: allowed, fan_names_allowed: allowed && fanNames }; if (config.storage_allowed && !allowed) { setConfirm({ type: 'settings', body }); return; } await saveSettings(body); }
  async function saveSettings(body) { setBusy(true); setError(''); try { const r = await api.patch('/settings', body); setConfig(r.data); setConfirm(null); toast.success('Configurações atualizadas.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function confirmAction() { if (confirm.type === 'settings') return saveSettings(confirm.body); setBusy(true); try { await api.delete(`/data?creator_id=${scope}`, { data: { reason } }); setConfirm(null); toast.success('Ação concluída e registrada no histórico.'); } catch (e) { toast.error(errorText(e)); } finally { setBusy(false); } }
  const getExtension = async () => { try { const r = await api.get('/extension/release'); await download('/extension/download', r.data.filename); toast.success('Extensão baixada.'); } catch (e) { toast.error(errorText(e)); } };
  return <><PageHeading eyebrow="CONTROLE DO WORKSPACE" title="Configurações" description="Sua equipe, a extensão e os limites dos seus dados."/>
    <section className="settings-section"><div><h2 data-testid="extension-settings-title">Extensão para Chrome</h2><p>Os chatters instalam a extensão no próprio Chrome. Sem instalador, sem bloqueio do Windows.</p></div><div className="form-stack settings-form"><div className="desktop-settings-links"><button className="settings-link-btn" data-testid="settings-download-extension" onClick={getExtension}><Download size={20}/><span><strong>Baixar a extensão (.zip)</strong><small>Carregar sem compactação em chrome://extensions</small></span><ArrowRight size={17}/></button><Link to="/instalar" data-testid="settings-extension-guide"><Puzzle size={20}/><span><strong>Guia de instalação</strong><small>Passo a passo para a equipe</small></span><ArrowRight size={17}/></Link></div><Notice id="extension-boundary" tone="">A extensão registra presença e turnos. Não lê mensagens, cookies ou usa a API da Privacy. O tempo de resposta e as vendas dependem de validação futura das telas.</Notice></div></section>
    <section className="settings-section"><div><h2 data-testid="preferences-title">Preferências da agência</h2><p>Fuso de Brasília · valores em reais.</p></div><form className="form-stack settings-form" onSubmit={save}><Field id="settings-agency-name" name="agency_name" label="Nome do workspace" defaultValue={config.agency_name} minLength={2} maxLength={70} required/><div className="form-columns"><Field id="settings-sla" name="sla_minutes" type="number" min={1} max={120} label="Meta de resposta (minutos)" defaultValue={config.sla_minutes} required/><Field id="settings-retention" name="retention_days" type="number" min={1} max={90} label="Retenção (dias)" defaultValue={config.retention_days} required/></div><div className="consent-block"><label className="checkbox-label"><input data-testid="settings-storage-consent" type="checkbox" checked={allowed} onChange={e => setAllowed(e.target.checked)}/><span>Confirmo que a agência pode conservar métricas e avaliações estruturadas para esta finalidade e que a equipe foi informada.</span></label><label className="checkbox-label"><input data-testid="settings-fan-names" type="checkbox" checked={allowed && fanNames} disabled={!allowed} onChange={e => setFanNames(e.target.checked)}/><span>Guardar o nome de exibição do assinante junto de esperas, respostas e vendas, para estudo de quem compra e responde. Só o nome, nunca o texto das mensagens; segue a mesma retenção. Desligar apaga os nomes já guardados.</span></label><p data-testid="storage-consent-note">A autorização de visualização, por si só, não autoriza copiar históricos. Nenhuma mensagem, mídia ou captura de tela será armazenada.</p></div><FormError error={error}/><div className="form-actions"><Submit id="save-settings" busy={busy}>Salvar preferências</Submit></div></form></section>
    <section className="settings-section"><div><h2 data-testid="delete-data-title">Exclusão antecipada</h2><p>Métricas e avaliações, sem remover contas ou perfis.</p></div><div className="form-stack settings-form"><Field id="delete-data-scope" label="Escopo"><Select id="delete-data-scope" value={scope} onChange={e => setScope(e.target.value)}><option value="">Todas as criadoras</option>{creators.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field id="delete-data-reason" label="Motivo da exclusão" value={reason} onChange={e => setReason(e.target.value)} minLength={5} maxLength={200} placeholder="Sem dados de assinantes ou mensagens"/><Button variant="destructive" data-testid="delete-data-button" disabled={reason.trim().length < 5} onClick={() => setConfirm({ type: 'delete' })}><Trash2 size={15}/>Excluir métricas e avaliações</Button></div></section>
    <section className="privacy-boundary"><ShieldCheck size={23}/><div><h2 data-testid="settings-boundary-title">A sessão fica onde deve ficar: no Chrome do chatter.</h2><p data-testid="settings-boundary-description">Login e verificações são manuais na Privacy. O Alta Pulse nunca recebe senhas, cookies ou conteúdo de conversa.</p></div></section>
    <Modal title={confirm?.type === 'settings' ? 'Desativar armazenamento de métricas?' : 'Confirmar exclusão de dados?'} open={!!confirm} onClose={() => setConfirm(null)} id="settings-confirm-modal"><p data-testid="settings-confirm-description" className="body-muted">{confirm?.type === 'settings' ? 'Ao desativar, as métricas e avaliações já armazenadas serão apagadas.' : 'As métricas e avaliações do escopo selecionado serão apagadas permanentemente. Esta ação não pode ser desfeita.'}</p><div className="form-actions"><Button variant="outline" data-testid="settings-cancel-action" onClick={() => setConfirm(null)}>Cancelar</Button><Button variant="destructive" data-testid="settings-confirm-action" disabled={busy} onClick={confirmAction}>Confirmar</Button></div></Modal>
  </>;
}
