// Boas-vindas motivacionais (aprovadas pelo Paulo em 01/10/2026): primeiro nome + frase sorteada,
// sem repetir até passar pelas 100 (ordem embaralhada guardada por usuário neste navegador).
export const PHRASES = [
 "Quem é a fera das vendas que vai vender tudo hoje? {nome}, hoje o dia é seu!",
 "Tava com saudade dessa máquina de vendas! Bora fazer o dia surreal, {nome}.",
 "Chegou quem eu tava esperando! Agora sim o bicho vai pegar, {nome}.",
 "{nome} na área! Hoje o caixa vai trabalhar dobrado.",
 "Bom te ver, {nome}! Cada conversa hoje é uma venda esperando acontecer.",
 "{nome}, a lenda voltou. Bora quebrar recorde?",
 "Atenção, equipe: {nome} entrou no jogo!",
 "{nome}, hoje é dia de fazer o extrato brilhar.",
 "Café tomado, {nome}? Então bora transformar papo em venda!",
 "{nome}, você não veio pra participar. Veio pra ganhar!",
 "Sentiu o cheiro de venda no ar, {nome}? É você chegando.",
 "{nome}, o turno começou e o placar tá zerado. Bora virar esse jogo!",
 "Quem chegou foi {nome}. Os fãs que se preparem!",
 "{nome}, sua meta de hoje: deixar a gente sem palavras.",
 "Prepara o dedo, {nome}: hoje é dia de responder rápido e vender muito.",
 "{nome}, você é a prova de que talento mais constância dá resultado.",
 "Bem-vindo de volta ao seu palco, {nome}!",
 "{nome}, hoje cada \"oi\" vira oportunidade.",
 "O dia só começou de verdade agora que {nome} chegou.",
 "{nome}, bora mostrar por que você é referência no time!",
 "Liga o modo fera, {nome}. Hoje não tem pra ninguém.",
 "{nome}, o fã certo tá esperando a mensagem certa. A sua!",
 "Chegou a energia que faltava! Bora, {nome}!",
 "{nome}, menos dúvida e mais venda. Você sabe fazer isso!",
 "Hoje o ranking tem nome e sobrenome: {nome}.",
 "{nome}, conversa boa vende sozinha, e você é craque nisso.",
 "Dia novo, meta nova, {nome} renovado. Bora!",
 "{nome}, faz hoje o que os outros vão tentar copiar amanhã.",
 "Olha quem chegou pra fazer história: {nome}!",
 "{nome}, o sucesso gosta de quem aparece. E você apareceu!",
 "Bora, {nome}! Cada resposta rápida é um passo pra cima.",
 "{nome}, hoje é dia de fazer o fã voltar sempre.",
 "Senta que lá vem venda! Bem-vindo, {nome}.",
 "{nome}, sua dedicação é o que faz a diferença. Bora brilhar!",
 "Quem tem {nome} no time não precisa de sorte.",
 "{nome}, hoje o \"talvez\" do fã vira \"quero\"!",
 "Modo turbo ativado, {nome}. Acelera!",
 "{nome}, cada fã atendido com carinho é dinheiro no caixa amanhã.",
 "Saudade de você, {nome}! Agora bora fazer acontecer.",
 "{nome}, ninguém segura quem tá com fome de resultado.",
 "Chegou {nome}: a parte boa do dia começa agora.",
 "{nome}, faz o simples bem feito e o resultado vem.",
 "Hoje o dia tem cara de recorde, {nome}. Concorda?",
 "{nome}, quem responde rápido vende primeiro. Bora!",
 "Bem-vindo, {nome}! Hoje você é o motor dessa operação.",
 "{nome}, transforma cada conversa numa experiência que o fã não esquece.",
 "A máquina ligou! Bom trabalho, {nome}.",
 "{nome}, hoje é dia de fazer o fã sentir que é único.",
 "Respira, sorri e vende, {nome}. Você manda bem demais!",
 "{nome}, o topo tá logo ali. Bora buscar?",
 "Chegou quem entende do assunto: {nome}!",
 "{nome}, hoje você vai surpreender até a si mesmo.",
 "Cada minuto conta, {nome}. E você faz cada um valer.",
 "{nome}, energia lá em cima que hoje o dia promete!",
 "Que bom ter você aqui, {nome}. Bora fazer bonito!",
 "{nome}, venda é consequência de conversa boa. E isso você tem de sobra.",
 "Pronto pro show, {nome}? A plateia tá esperando.",
 "{nome}, hoje o \"visto\" vai virar \"pago\".",
 "Quem chegou chegando? {nome}, claro!",
 "{nome}, o seu melhor dia de vendas pode ser hoje.",
 "Foco, carisma e agilidade: o kit {nome} tá completo!",
 "{nome}, bora fazer o fã abrir a carteira sorrindo.",
 "Mais um dia pra mostrar do que você é capaz, {nome}.",
 "{nome}, confia no seu talento. Ele nunca te deixou na mão.",
 "O time fica mais forte quando {nome} chega!",
 "{nome}, hoje é dia de oferta certeira.",
 "Tá on, {nome}? Então o faturamento também tá!",
 "{nome}, persistência é seu superpoder. Usa sem moderação.",
 "Bem-vindo, {nome}! Vamos transformar atenção em resultado.",
 "{nome}, o fã que sumiu ontem pode ser a venda de hoje.",
 "Começou o expediente da fera: {nome} on!",
 "{nome}, cada conversa é uma chance nova de brilhar.",
 "Bora, {nome}! O dia tá cheio de oportunidade esperando você.",
 "{nome}, quem cuida bem do fã nunca fica sem venda.",
 "Chegou o terror das metas! Bom te ver, {nome}.",
 "{nome}, hoje é dia de fazer o difícil parecer fácil.",
 "Atenção, fãs: {nome} tá online e com tudo!",
 "{nome}, uma mensagem bem feita vale mais que dez apressadas.",
 "Seu turno, suas regras, seu resultado, {nome}. Bora!",
 "{nome}, o extrato de hoje vai ter a sua assinatura.",
 "Que comecem as vendas! Bem-vindo, {nome}.",
 "{nome}, ritmo bom é ritmo constante. Mantém que vem!",
 "Tá vendo esse dia lindo, {nome}? Ele é todo seu.",
 "{nome}, você faz o fã se sentir especial, e isso não tem preço. Mas tem venda!",
 "Bora pra cima, {nome}! Hoje ninguém segura.",
 "{nome}, primeiro a gente encanta, depois a gente vende.",
 "O jogo virou: {nome} entrou em campo!",
 "{nome}, cada pequena venda soma um dia gigante.",
 "Que alegria te ver, {nome}! Bora fazer valer.",
 "{nome}, hoje é dia de atender como se fosse o primeiro fã do mundo.",
 "Força, foco e venda, {nome}!",
 "{nome}, seu esforço de hoje é o resultado de amanhã.",
 "Chegou a pessoa que faz o caixa sorrir: {nome}!",
 "{nome}, sem fã esperando hoje. Responde rapidinho e domina!",
 "Partiu bater meta, {nome}? Eu aposto em você.",
 "{nome}, quem é bom nisso é você. Mostra pra eles!",
 "A fera acordou! Bom turno, {nome}.",
 "{nome}, hoje é dia de deixar marca no ranking.",
 "Bem-vindo de volta, {nome}! O sucesso tava te esperando.",
 "{nome}, respira fundo: hoje vai ser surreal!"
];
export function nextPhrase(userId, name) {
  const first = String(name || '').trim().split(/\s+/)[0] || 'você';
  const key = `alta-frases-${userId || 'anon'}`;
  let st = null; try { st = JSON.parse(localStorage.getItem(key) || 'null'); } catch {}
  if (!st || !Array.isArray(st.order) || st.order.length !== PHRASES.length || st.i >= PHRASES.length) {
    const order = PHRASES.map((_, i) => i);
    for (let i = order.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [order[i], order[j]] = [order[j], order[i]]; }
    st = { order, i: 0 };
  }
  const text = PHRASES[st.order[st.i]].replace(/\{nome\}/g, first);
  st.i += 1; try { localStorage.setItem(key, JSON.stringify(st)); } catch {}
  return text;
}
