// Boas-vindas (formato aprovado pelo Paulo em 01/10/2026): "Oi, <primeiro nome>! 👋" + foto, uma frase
// sorteada (sem repetir até passar pelas 100) e a assinatura "Time Alta". Conta Admin recebe só "Oi! 👋".
export const PHRASES = [
 "Hoje é dia da fera das vendas vender tudo! O dia é seu 🔥",
 "Tava com saudade dessa máquina de vendas! Bora fazer o dia surreal 🚀",
 "Chegou quem eu tava esperando! Agora sim o bicho vai pegar 😎",
 "Você na área! Hoje o caixa vai trabalhar dobrado 💰",
 "Cada conversa hoje é uma venda esperando acontecer ✨",
 "A lenda voltou. Bora quebrar recorde? 🏆",
 "Atenção, equipe: entrou no jogo quem faz acontecer! ⚡",
 "Hoje é dia de fazer o extrato brilhar 💎",
 "Café tomado? Então bora transformar papo em venda! ☕",
 "Você não veio pra participar. Veio pra ganhar! 🥇",
 "Sentiu o cheiro de venda no ar? É você chegando 😏",
 "O turno começou e o placar tá zerado. Bora virar esse jogo! ⚽",
 "Os fãs que se preparem, porque você chegou! 🔥",
 "Sua meta de hoje: deixar a gente sem palavras 🤩",
 "Prepara o dedo: hoje é dia de responder rápido e vender muito ⚡",
 "Você é a prova de que talento mais constância dá resultado 💪",
 "De volta ao seu palco! Bora brilhar 🌟",
 "Hoje cada \"oi\" vira oportunidade 💬",
 "O dia só começou de verdade agora que você chegou ☀️",
 "Bora mostrar por que você é referência no time! 👑",
 "Liga o modo fera. Hoje não tem pra ninguém 🦁",
 "O fã certo tá esperando a mensagem certa. A sua! 💌",
 "Chegou a energia que faltava! Bora! ⚡",
 "Menos dúvida e mais venda. Você sabe fazer isso! 💪",
 "Hoje o topo do ranking tem a sua cara 🏆",
 "Conversa boa vende sozinha, e você é craque nisso 🎯",
 "Dia novo, meta nova, energia renovada. Bora! 🔋",
 "Faz hoje o que os outros vão tentar copiar amanhã 😎",
 "Olha quem chegou pra fazer história! 📈",
 "O sucesso gosta de quem aparece. E você apareceu! ✨",
 "Cada resposta rápida é um passo pra cima 🚀",
 "Hoje é dia de fazer o fã voltar sempre ❤️",
 "Senta que lá vem venda! 💸",
 "Sua dedicação é o que faz a diferença. Bora brilhar! 🌟",
 "Quem tem você no time não precisa de sorte 🍀",
 "Hoje o \"talvez\" do fã vira \"quero\"! 😍",
 "Modo turbo ativado. Acelera! 🏎️",
 "Cada fã atendido com carinho é dinheiro no caixa amanhã 💰",
 "Que saudade! Agora bora fazer acontecer 🙌",
 "Ninguém segura quem tá com fome de resultado 🔥",
 "Você chegou e a parte boa do dia começou agora 🎉",
 "Faz o simples bem feito e o resultado vem ✅",
 "Hoje o dia tem cara de recorde. Concorda? 📊",
 "Quem responde rápido vende primeiro. Bora! ⏱️",
 "Hoje você é o motor dessa operação 🚂",
 "Transforma cada conversa numa experiência que o fã não esquece 💫",
 "A máquina ligou! Bom trabalho 🤖",
 "Hoje é dia de fazer o fã sentir que é único 💖",
 "Respira, sorri e vende. Você manda bem demais! 😄",
 "O topo tá logo ali. Bora buscar? ⛰️",
 "Chegou quem entende do assunto! 🧠",
 "Hoje você vai se surpreender com o que é capaz de fazer 🤯",
 "Cada minuto conta. E você faz cada um valer ⏳",
 "Energia lá em cima, que hoje o dia promete! ⚡",
 "Que bom ter você aqui. Bora fazer bonito! 😉",
 "Venda é consequência de conversa boa. E isso você tem de sobra 💬",
 "Bora pro show? A plateia tá esperando 🎤",
 "Hoje o \"visto\" vai virar \"pago\" ✔️",
 "Quem chegou chegando? Você, claro! 😎",
 "O seu melhor dia de vendas pode ser hoje 📈",
 "Foco, carisma e agilidade: o kit tá completo! 🧰",
 "Bora fazer o fã abrir a carteira sorrindo 😁",
 "Mais um dia pra mostrar do que você é capaz 💪",
 "Confia no seu talento. Ele nunca te deixou na mão 🙏",
 "O time fica mais forte quando você chega! 🤝",
 "Hoje é dia de oferta certeira 🎯",
 "Tá on? Então o faturamento também tá! 💸",
 "Persistência é seu superpoder. Usa sem moderação 🦸",
 "Bora transformar atenção em resultado! 📲",
 "O fã que sumiu ontem pode ser a venda de hoje 🔄",
 "Começou o expediente da fera! 🐯",
 "Cada conversa é uma chance nova de brilhar ✨",
 "O dia tá cheio de oportunidade esperando você! 🌈",
 "Quem cuida bem do fã nunca fica sem venda 💕",
 "Chegou o terror das metas! Bom te ver 😈",
 "Hoje é dia de fazer o difícil parecer fácil 😌",
 "Atenção, fãs: você tá online e com tudo! 📣",
 "Uma mensagem bem feita vale mais que dez apressadas ✍️",
 "Seu turno, suas regras, seu resultado. Bora! 🏁",
 "O extrato de hoje vai ter a sua assinatura ✒️",
 "Que comecem as vendas! 🎬",
 "Ritmo bom é ritmo constante. Mantém que vem! 🥁",
 "Tá vendo esse dia lindo? Ele é todo seu 🌞",
 "Você faz o fã se sentir especial, e isso não tem preço. Mas tem venda! 💝",
 "Bora pra cima! Hoje ninguém segura 🚀",
 "Primeiro a gente encanta, depois a gente vende 🪄",
 "O jogo virou: você entrou em campo! ⚽",
 "Cada pequena venda soma um dia gigante 🧱",
 "Que alegria te ver! Bora fazer valer 🥳",
 "Hoje é dia de atender como se fosse o primeiro fã do mundo 🌍",
 "Força, foco e venda! 💥",
 "Seu esforço de hoje é o resultado de amanhã 🌱",
 "Chegou quem faz o caixa sorrir! 🤑",
 "Nenhum fã esperando hoje: responde rapidinho e domina! ⚡",
 "Partiu bater meta? Eu aposto em você 🎲",
 "Quem é bom nisso é você. Mostra pra eles! 👊",
 "A fera acordou! Bom turno 🐆",
 "Hoje é dia de deixar marca no ranking 🥇",
 "O sucesso tava te esperando! 🎯",
 "Respira fundo: hoje vai ser surreal! 🌪️"
];
export const SIGNATURE = 'Atenciosamente, Time Alta ❤️';
export const greetName = (name) => { const n = String(name || '').trim(); if (/^(admin|time)\b/i.test(n)) return ''; return n.split(/\s+/)[0] || ''; };
export const greeting = (name) => { const f = greetName(name); return f ? `Oi, ${f}! 👋` : 'Oi! 👋'; };
export function nextPhrase(userId) {
  const key = `alta-frases2-${userId || 'anon'}`;
  let st = null; try { st = JSON.parse(localStorage.getItem(key) || 'null'); } catch {}
  if (!st || !Array.isArray(st.order) || st.order.length !== PHRASES.length || st.i >= PHRASES.length) {
    const order = PHRASES.map((_, i) => i);
    for (let i = order.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [order[i], order[j]] = [order[j], order[i]]; }
    st = { order, i: 0 };
  }
  const text = PHRASES[st.order[st.i]];
  st.i += 1; try { localStorage.setItem(key, JSON.stringify(st)); } catch {}
  return text;
}
