const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pulse', {
  login: (email, password) => ipcRenderer.invoke('auth:login', { email, password }),
  logout: () => ipcRenderer.invoke('auth:logout'),
  getState: () => ipcRenderer.invoke('state:get'),
  reloadActive: () => ipcRenderer.invoke('profile:reload-active'),
  snapshot: () => ipcRenderer.invoke('state:snapshot'),

  openProfile: (id, platform) => ipcRenderer.invoke('profile:open', id, platform),
  vaultUse: (id, platform) => ipcRenderer.invoke('vault:use', id, platform),
  vaultEnter: (id, platform) => ipcRenderer.invoke('vault:enter', id, platform),
  showProfile: (id, platform) => ipcRenderer.invoke('profile:show', id, platform),
  closeTab: (id, platform) => ipcRenderer.invoke('profile:closeTab', id, platform),
  closeProfile: (id) => ipcRenderer.invoke('profile:close', id),
  reloadProfile: (id) => ipcRenderer.invoke('profile:reload', id),
  backProfile: (id) => ipcRenderer.invoke('profile:back', id),
  clearProfile: (id, what) => ipcRenderer.invoke('profile:clear', { id, what }),
  hideAll: () => ipcRenderer.invoke('profile:hideAll'),
  calibrate: (id) => ipcRenderer.invoke('profile:calibrate', id),
  readExtrato: (id) => ipcRenderer.invoke('extrato:read', id),
  toggleExtrato: (id) => ipcRenderer.invoke('extrato:toggle', id),
  calibrateStats: (id, tour) => ipcRenderer.invoke('extrato:calibrate', id, tour),

  startShift: (creatorId) => ipcRenderer.invoke('shift:start', creatorId),
  shiftAction: (shiftId, action) => ipcRenderer.invoke('shift:action', { shiftId, action }),
  shiftAnswer: (a) => ipcRenderer.invoke('shiftclock:answer', a),
  onShiftPrompt: (fn) => ipcRenderer.on('shiftclock:prompt', (_e, p) => fn(p)),

  setCreatorLocal: (id, patch) => ipcRenderer.invoke('local:setCreator', { id, patch }),
  setGroups: (groups) => ipcRenderer.invoke('local:setGroups', groups),
  setOrder: (order) => ipcRenderer.invoke('order:set', order),
  setTags: (tags) => ipcRenderer.invoke('local:setTags', tags),
  setOrigin: (origin) => ipcRenderer.invoke('config:setOrigin', origin),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  appInfo: () => ipcRenderer.invoke('app:info'),
  setAvatar: (image) => ipcRenderer.invoke('me:avatar', image),

  onState: (fn) => ipcRenderer.on('state', (_e, s) => fn(s)),
  onFan: (fn) => ipcRenderer.on('fan', (_e, f) => fn(f)),
  fanCollapse: (collapsed) => ipcRenderer.invoke('fan:collapse', collapsed),
  assistStatus: (force) => ipcRenderer.invoke('assist:status', force),
  assistRun: (opts) => ipcRenderer.invoke('assist:run', opts),
  assistUse: (text) => ipcRenderer.invoke('assist:use', text),
  fanRefresh: () => ipcRenderer.invoke('fan:refresh'),
  fanNoteAdd: (text) => ipcRenderer.invoke('fan:note:add', text),
  fanNoteDel: (id) => ipcRenderer.invoke('fan:note:del', id),
  fanContacted: (taskId) => ipcRenderer.invoke('fan:contacted', taskId),
  taskOpen: (taskId) => ipcRenderer.invoke('task:open', taskId),
  onToast: (fn) => ipcRenderer.on('toast', (_e, m) => fn(m)),
  onPortableUpdate: (fn) => ipcRenderer.on('portable-update', (_e, m) => fn(m)),
});
